#!/usr/bin/env python3
"""Splits the satellite dish modelled in Blender (source/antena.obj, exported
from source/antena.blend) into the two parts the Satellite class moves:

  antenna_base.obj  the block it stands on (the mount): origin at the centre of
                    its bottom face, on the ground; it only turns around +y
                    (the azimuth).
  antenna_dish.obj  the dish, the arm and the receiver (the head): origin on
                    the hinge, the dish's lowest edge, with the boresight (the
                    arm) along +y. The Satellite tilts it around the hinge
                    (x axis) by the zenith, towards -z, then turns it with the
                    azimuth.

Both are turned 180 degrees around +y first: in Blender the dish faces +z,
and the Satellite's azimuth 0 is north (-z). Each part gets a flat colour
(no textures). Prints the hinge in the base's frame: it must match HINGE in
src/entities/Satellite.cpp.

Usage: python3 split_antenna.py        (writes next to this script)
Needs numpy.
"""
import os
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
SOURCE = os.path.join(HERE, 'source', 'antena.obj')

# Flat colours (Kd) of each part
COLOURS = {
    'base': (0.32, 0.33, 0.35),     # dark grey metal
    'dish': (0.86, 0.87, 0.88),     # painted white
    'arm': (0.55, 0.56, 0.58),      # grey
    'receiver': (0.20, 0.20, 0.22), # dark
}


def load(path):
    vertices, normals, faces = [], [], []
    for line in open(path):
        p = line.split()
        if not p:
            continue
        if p[0] == 'v':
            vertices.append([float(x) for x in p[1:4]])
        elif p[0] == 'vn':
            normals.append([float(x) for x in p[1:4]])
        elif p[0] == 'f':
            corners = []
            for token in p[1:]:
                parts = token.split('/')
                corners.append((int(parts[0]) - 1, int(parts[2]) - 1))
            faces.append(corners)
    return np.array(vertices), np.array(normals), faces


def components(vertices, faces):
    """Groups of faces joined by shared vertices (or vertices in the same place)"""
    parent = list(range(len(vertices)))

    def find(i):
        while parent[i] != i:
            parent[i] = parent[parent[i]]
            i = parent[i]
        return i
    for face in faces:
        for v, _ in face[1:]:
            parent[find(v)] = find(face[0][0])
    seen = {}
    for i, v in enumerate(vertices):
        key = tuple(np.round(v, 4))
        if key in seen:
            parent[find(i)] = find(seen[key])
        else:
            seen[key] = i
    groups = {}
    for f, face in enumerate(faces):
        groups.setdefault(find(face[0][0]), []).append(f)
    return list(groups.values())


def rotation_x(angle):
    c, s = np.cos(angle), np.sin(angle)
    return np.array([[1, 0, 0], [0, c, -s], [0, s, c]])


def write(name, parts, vertices, normals, faces, transform, rotation):
    """parts: [(part name, face indices)]; transform maps points, rotation
    the normals"""
    obj = ['# Generated by split_antenna.py from source/antena.obj',
           'mtllib %s.mtl' % name, 'o %s' % name]
    mtl = ['# Generated by split_antenna.py']
    used_v, used_n = {}, {}
    body = []
    for part, face_ids in parts:
        body.append('usemtl %s' % part)
        mtl += ['newmtl %s' % part, 'Kd %.3f %.3f %.3f' % COLOURS[part],
                'Ks 0.300 0.300 0.300', 'Ns 60', 'd 1.0', 'illum 2', '']
        for f in face_ids:
            corners = []
            for v, n in faces[f]:
                if v not in used_v:
                    used_v[v] = len(used_v) + 1
                if n not in used_n:
                    used_n[n] = len(used_n) + 1
                corners.append('%d//%d' % (used_v[v], used_n[n]))
            body.append('f ' + ' '.join(corners))
    for v in sorted(used_v, key=used_v.get):
        obj.append('v %.6f %.6f %.6f' % tuple(transform(vertices[v])))
    for n in sorted(used_n, key=used_n.get):
        obj.append('vn %.6f %.6f %.6f' % tuple(rotation @ normals[n]))
    obj += body
    open(os.path.join(HERE, name + '.obj'), 'w').write('\n'.join(obj) + '\n')
    open(os.path.join(HERE, name + '.mtl'), 'w').write('\n'.join(mtl))


def main():
    vertices, normals, faces = load(SOURCE)
    # The parts, told apart by their shape: the base is a block (6 faces) at
    # the bottom, the receiver the most detailed (a sphere), the arm the
    # smallest box and the dish the biggest
    groups = components(vertices, faces)
    assert len(groups) == 4, 'expected base, dish, arm and receiver'

    def size(g):
        points = vertices[[v for f in g for v, _ in faces[f]]]
        return np.prod(points.max(0) - points.min(0) + 1e-6)
    by_faces = sorted(groups, key=len)
    base = [g for g in groups if len(g) == 6][0]
    rest = [g for g in groups if g is not base]
    receiver = max(rest, key=len)
    rest = [g for g in rest if g is not receiver]
    dish = max(rest, key=size)
    arm = [g for g in rest if g is not dish][0]

    # Turned to face north (-z): 180 degrees around +y
    turn = np.diag([-1.0, 1.0, -1.0])
    points = vertices @ turn.T
    base_points = points[[v for f in base for v, _ in faces[f]]]
    bottom = base_points[:, 1].min()

    # The boresight is along the arm (its longest axis), away from the dish
    arm_points = points[[v for f in arm for v, _ in faces[f]]]
    centred = arm_points - arm_points.mean(0)
    axis = np.linalg.eigh(centred.T @ centred)[1][:, -1]
    if axis[1] < 0:
        axis = -axis
    zenith = np.arccos(axis[1])  # towards -z after the turn
    # The hinge: the middle of the dish's lowest edge
    dish_points = points[[v for f in dish for v, _ in faces[f]]]
    lowest = dish_points[dish_points[:, 1] < dish_points[:, 1].min() + 1e-3]
    hinge = np.array([0.0, lowest[:, 1].mean(), lowest[:, 2].mean()])

    # Base: on the ground, centred
    write('antenna_base', [('base', base)], vertices, normals, faces,
          lambda v: turn @ v - np.array([0.0, bottom, 0.0]), turn)
    # Head: about the hinge, tilted back up so that the boresight is +y (the
    # Satellite tilts it towards -z by the zenith)
    up = rotation_x(zenith)
    write('antenna_dish', [('dish', dish), ('arm', arm), ('receiver', receiver)],
          vertices, normals, faces, lambda v: up @ (turn @ v - hinge), up @ turn)

    head = np.array([up @ (p - hinge) for p in
                     points[[v for g in (dish, arm, receiver) for f in g for v, _ in faces[f]]]])
    print('modelled zenith: %.1f degrees' % np.degrees(zenith))
    print('HINGE (base frame): (%.3f, %.3f, %.3f)' % (hinge[0], hinge[1] - bottom, hinge[2]))
    print('head bounds:', head.min(0).round(3), head.max(0).round(3))


if __name__ == '__main__':
    main()
