#!/usr/bin/env python3
"""Generates a wooden sign (OBJ + MTL + JPG) for the Readable objects.

Usage: python3 generate_sign.py        (writes next to this script)
Needs numpy and Pillow. Seeded, so the output is reproducible.

The origin is at the foot of the post; +y is up and the board faces +z.
The board's front shows "AVISO" and a few painted lines (the real text is
in the game's dialogue box). Texture atlas, 512x256:
  x 0..384   the board's front
  x 384..512 plain wood for everything else
"""
import os
import numpy as np
from PIL import Image, ImageDraw, ImageFont

OUT = os.path.dirname(os.path.abspath(__file__))
W, H = 512, 256
FRONT = (0, 0, 384, 256)    # atlas rectangle (x0, y0, x1, y1), y down
PLAIN = (384, 0, 512, 256)

POST = (0.07, 1.25)         # half width, height
BOARD = (0.6, 0.38, 0.03, 1.30)  # half width, half height, half depth, centre y
FONT = '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'


def wood(w, h, rng, base):
    """Planks running horizontally, with grain."""
    y = np.arange(h)[:, None]
    x = np.arange(w)[None, :]
    grain = np.sin(x * 0.05 + np.sin(y * 0.3) * 2.0 + rng.uniform(0, 6)) * 0.5 + 0.5
    noise = rng.random((h, w)) * 0.15
    shade = 0.75 + 0.2 * grain + noise
    shade = shade * np.where((y % 64) < 3, 0.6, 1.0)  # gaps between planks
    img = np.clip(np.array(base)[None, None, :] * shade[..., None], 0, 255)
    return Image.fromarray(img.astype(np.uint8))


def make_texture():
    rng = np.random.default_rng(7)
    img = Image.new('RGB', (W, H))
    img.paste(wood(FRONT[2] - FRONT[0], FRONT[3] - FRONT[1], rng, (170, 120, 70)),
              FRONT[:2])
    img.paste(wood(PLAIN[2] - PLAIN[0], PLAIN[3] - PLAIN[1], rng, (120, 82, 48)),
              PLAIN[:2])
    draw = ImageDraw.Draw(img)
    x0, y0, x1, y1 = FRONT
    draw.rectangle([x0 + 4, y0 + 4, x1 - 5, y1 - 5], outline=(70, 45, 25), width=8)
    try:
        font = ImageFont.truetype(FONT, 64)
    except OSError:
        font = ImageFont.load_default()
    text = 'AVISO'
    box = draw.textbbox((0, 0), text, font=font)
    draw.text(((x0 + x1 - (box[2] - box[0])) / 2, y0 + 30), text,
              fill=(40, 25, 15), font=font)
    for i in range(4):  # painted lines standing for the small print
        y = y0 + 125 + i * 28
        draw.line([x0 + 50, y, x1 - 50 - (i % 2) * 70, y], fill=(60, 38, 22), width=7)
    img.save(os.path.join(OUT, 'sign.jpg'), quality=92)


def uv(rect, u, v):
    """(u, v) in 0..1 across `rect` -> OBJ texture coordinates (v up)."""
    x0, y0, x1, y1 = rect
    return ((x0 + u * (x1 - x0)) / W, 1 - (y1 - v * (y1 - y0)) / H)


def box(lines, counts, lo, hi, front=None):
    """Axis-aligned box from `lo` to `hi`; its +z face uses `front` if given."""
    (x0, y0, z0), (x1, y1, z1) = lo, hi
    faces = [  # corners counter-clockwise seen from outside, normal
        ([(x0, y0, z1), (x1, y0, z1), (x1, y1, z1), (x0, y1, z1)], (0, 0, 1)),
        ([(x1, y0, z0), (x0, y0, z0), (x0, y1, z0), (x1, y1, z0)], (0, 0, -1)),
        ([(x1, y0, z1), (x1, y0, z0), (x1, y1, z0), (x1, y1, z1)], (1, 0, 0)),
        ([(x0, y0, z0), (x0, y0, z1), (x0, y1, z1), (x0, y1, z0)], (-1, 0, 0)),
        ([(x0, y1, z1), (x1, y1, z1), (x1, y1, z0), (x0, y1, z0)], (0, 1, 0)),
        ([(x0, y0, z0), (x1, y0, z0), (x1, y0, z1), (x0, y0, z1)], (0, -1, 0)),
    ]
    for corners, normal in faces:
        rect = front if (front and normal == (0, 0, 1)) else PLAIN
        v, t, n = counts
        for x, y, z in corners:
            lines.append(f'v {x:.4f} {y:.4f} {z:.4f}')
        for cu, cv in ((0, 0), (1, 0), (1, 1), (0, 1)):
            lines.append('vt %.5f %.5f' % uv(rect, cu, cv))
        lines.append('vn %d %d %d' % normal)
        idx = [f'{v + k + 1}/{t + k + 1}/{n + 1}' for k in range(4)]
        lines.append(f'f {idx[0]} {idx[1]} {idx[2]}')
        lines.append(f'f {idx[0]} {idx[2]} {idx[3]}')
        counts[0] += 4
        counts[1] += 4
        counts[2] += 1


def make_obj():
    lines = ['# generated by generate_sign.py', 'mtllib sign.mtl', 'o sign',
             'usemtl sign']
    counts = [0, 0, 0]
    pw, ph = POST
    box(lines, counts, (-pw, 0.0, -pw), (pw, ph, pw))
    bw, bh, bd, by = BOARD
    box(lines, counts, (-bw, by - bh, pw), (bw, by + bh, pw + 2 * bd), FRONT)
    with open(os.path.join(OUT, 'sign.obj'), 'w') as f:
        f.write('\n'.join(lines) + '\n')
    with open(os.path.join(OUT, 'sign.mtl'), 'w') as f:
        f.write('# generated by generate_sign.py\nnewmtl sign\nNs 10\nKa 1 1 1\n'
                'Kd 1 1 1\nKs 0 0 0\nillum 1\nmap_Kd sign.jpg\n')


if __name__ == '__main__':
    make_texture()
    make_obj()
