"""Generates needle.obj / needle.mtl: the red needle of a gauge of the RV's dashboard, in a
model of its own (the dashboard has the dial but not the needle, so that it can turn).
The same model serves for every gauge. Meters.

Its own frame: the origin is the pivot (the centre of the gauge), the needle is flat in the
XY plane, pointing along +Y when its angle is 0, and +Z is out of the dial (towards the
driver): the needle turns around Z, counter-clockwise seen from the driver (from +Z).
Where it goes on dashboard.obj, and between which angles, is in dashboard_mounts.json (see
generate_dashboard.py). The hub (the chrome cap over the pivot) is part of the dashboard, which does not turn;
the needle is drawn emissive (it glows) when the dashboard lights are on.
"""
import math

objs = []  # (material, verts, faces)


def vol(verts, faces):
    s = 0
    for f in faces:
        a = verts[f[0]]
        for i in range(1, len(f) - 1):
            b, c = verts[f[i]], verts[f[i + 1]]
            s += (a[0]*(b[1]*c[2]-b[2]*c[1]) - a[1]*(b[0]*c[2]-b[2]*c[0]) + a[2]*(b[0]*c[1]-b[1]*c[0]))
    return s


def add(mat, verts, faces):
    """Closed solids only: the faces are turned to face outwards."""
    if vol(verts, faces) < 0:
        faces = [f[::-1] for f in faces]
    objs.append((mat, list(verts), faces))


def plate(mat, outline, z0, z1):
    """A flat plate: the (x, y) outline (a simple polygon) extruded from z0 to z1."""
    n = len(outline)
    verts = [(x, y, z0) for x, y in outline] + [(x, y, z1) for x, y in outline]
    faces = [list(range(n)), list(range(2*n-1, n-1, -1))]
    for i in range(n):
        j = (i + 1) % n
        faces.append([i, n+i, n+j, j])
    add(mat, verts, faces)


def cylinder(mat, r, z0, z1, seg=24):
    verts = [(r*math.cos(2*math.pi*i/seg), r*math.sin(2*math.pi*i/seg), z) for z in (z0, z1) for i in range(seg)]
    faces = [list(range(seg)), list(range(2*seg-1, seg-1, -1))]
    for i in range(seg):
        j = (i + 1) % seg
        faces.append([i, seg+i, seg+j, j])
    add(mat, verts, faces)


LENGTH = 0.050        # from the pivot to the tip
TAIL = 0.012          # the short counterweight on the other side
# the pointer, tapering to the tip, and a small round tail
outline = [(0.0035, 0.002), (0.0009, LENGTH), (-0.0009, LENGTH), (-0.0035, 0.002),
           (-0.0045, -0.006), (-0.0030, -TAIL), (0.0030, -TAIL), (0.0045, -0.006)]
plate('redneedle', outline, 0.000, 0.003)

MATS = {'redneedle': (0.88, 0.06, 0.04)}
with open('needle.mtl', 'w') as f:
    f.write('# generated by generate_needle.py\n')
    for n, c in MATS.items():
        f.write(f'newmtl {n}\nKa {c[0]:.3f} {c[1]:.3f} {c[2]:.3f}\nKd {c[0]:.3f} {c[1]:.3f} {c[2]:.3f}\n'
                'Ks 0.05 0.05 0.05\nNs 10\nillum 2\n\n')
with open('needle.obj', 'w') as f:
    f.write('# generated by generate_needle.py\nmtllib needle.mtl\no needle\n')
    off = 0
    for cnt, (mat, verts, faces) in enumerate(objs):
        f.write(f'g part{cnt}\nusemtl {mat}\n')
        for v in verts:
            f.write('v %.5f %.5f %.5f\n' % v)
        for fc in faces:
            f.write('f ' + ' '.join(str(i + 1 + off) for i in fc) + '\n')
        off += len(verts)
print(len(objs), 'parts,', off, 'vertices')
