"""Generates key.obj / key.mtl: a key, in a model of its own (the RV's ignition key; it is
separate from the dashboard so that it can be moved on its own later: turned in the lock,
picked up, carried...). Meters, real size (a car key: ~11 cm long).

Its own frame: the origin is where the blade meets the head (the shoulder of the key),
+Z is the axis of the key pointing out of the lock towards the head, so the blade goes
towards -Z (into the lock), +Y is the width of the blade (the teeth are on its -Y edge)
and +X is the thickness (the key is flat in the YZ plane), so X = Y x Z.
Put in the ignition of dashboard.obj with the placement written in dashboard_mounts.json
(see generate_dashboard.py).
"""
import math

objs = []  # (material, verts, faces)


def vol(verts, faces):
    s = 0
    for f in faces:
        a = verts[f[0]]
        for i in range(1, len(f) - 1):
            b, c = verts[f[i]], verts[f[i + 1]]
            s += (a[0]*(b[1]*c[2]-b[2]*c[1]) - a[1]*(b[0]*c[2]-b[2]*c[0]) + a[2]*(b[0]*c[1]-b[1]*c[0]))
    return s


def add(mat, verts, faces):
    """Closed solids only: the faces are turned to face outwards."""
    if vol(verts, faces) < 0:
        faces = [f[::-1] for f in faces]
    objs.append((mat, list(verts), faces))


def box(mat, x0, x1, y0, y1, z0, z1):
    v = [(x0, y0, z0), (x1, y0, z0), (x1, y0, z1), (x0, y0, z1),
         (x0, y1, z0), (x1, y1, z0), (x1, y1, z1), (x0, y1, z1)]
    add(mat, v, [[0, 3, 2, 1], [4, 5, 6, 7], [0, 1, 5, 4], [1, 2, 6, 5], [2, 3, 7, 6], [3, 0, 4, 7]])


def prism(mat, prof, x0, x1):
    """The profile (z, y points) extruded along x (any simple polygon)."""
    n = len(prof)
    verts = [(x0, y, z) for z, y in prof] + [(x1, y, z) for z, y in prof]
    faces = [list(range(n)), list(range(2*n-1, n-1, -1))]
    for i in range(n):
        j = (i + 1) % n
        faces.append([i, n+i, n+j, j])
    add(mat, verts, faces)


def ring_prism(mat, outer, inner, x0, x1):
    """A flat plate with a hole: `outer` and `inner` are (z, y) loops with the same
    number of points, around the same turn, extruded along x."""
    n = len(outer)
    verts = ([(x0, y, z) for z, y in outer] + [(x1, y, z) for z, y in outer] +
             [(x0, y, z) for z, y in inner] + [(x1, y, z) for z, y in inner])
    O0, O1, I0, I1 = 0, n, 2*n, 3*n
    faces = []
    for i in range(n):
        j = (i + 1) % n
        faces.append([O0+i, O0+j, I0+j, I0+i])        # the face at x0, between the two loops
        faces.append([O1+i, I1+i, I1+j, O1+j])        # the face at x1
        faces.append([O0+i, O1+i, O1+j, O0+j])        # the outside wall
        faces.append([I0+i, I0+j, I1+j, I1+i])        # the wall of the hole
    add(mat, verts, faces)


# ------------------------------------------------------------------------ the blade
# its profile (z, y): the straight back edge on top (y = +0.007) and the teeth on the
# bottom edge, from the tip (z = -0.047) to the shoulder (z = 0)
BLADE = [(0.0, 0.007), (-0.047, 0.007), (-0.047, 0.001), (-0.044, -0.005), (-0.038, -0.005), (-0.038, -0.002),
         (-0.032, -0.002), (-0.032, -0.0065), (-0.025, -0.0065), (-0.025, -0.003), (-0.019, -0.003),
         (-0.019, -0.007), (-0.012, -0.007), (-0.012, -0.0035), (-0.006, -0.0035), (-0.006, -0.007),
         (0.0, -0.007)]
prism('brass', BLADE, -0.0013, 0.0013)
# the shoulder: a small stop that keeps the key from going in too far
box('brass', -0.0030, 0.0030, -0.0095, 0.0095, 0.0, 0.0035)

# ------------------------------------------------------------------------- the head
# a black plastic bow with a hole for a key ring: a neck, then a rounded plate
box('plastic', -0.0032, 0.0032, -0.0075, 0.0075, 0.0035, 0.0140)
SEG = 36
HEAD_Z, HEAD_RY, HEAD_RZ = 0.038, 0.0185, 0.0255          # the rounded plate (an ellipse)
HOLE_Z, HOLE_R = 0.0505, 0.0050                             # the hole, near the far end
outer = [(HEAD_Z + HEAD_RZ * math.cos(2*math.pi*i/SEG), HEAD_RY * math.sin(2*math.pi*i/SEG)) for i in range(SEG)]
inner = [(HOLE_Z + HOLE_R * math.cos(2*math.pi*i/SEG), HOLE_R * math.sin(2*math.pi*i/SEG)) for i in range(SEG)]
ring_prism('plastic', outer, inner, -0.0032, 0.0032)

MATS = {'brass': (0.80, 0.64, 0.24), 'plastic': (0.05, 0.05, 0.06)}
with open('key.mtl', 'w') as f:
    f.write('# generated by generate_key.py\n')
    for n, c in MATS.items():
        f.write(f'newmtl {n}\nKa {c[0]:.3f} {c[1]:.3f} {c[2]:.3f}\nKd {c[0]:.3f} {c[1]:.3f} {c[2]:.3f}\n'
                'Ks 0.30 0.30 0.30\nNs 40\nillum 2\n\n')
with open('key.obj', 'w') as f:
    f.write('# generated by generate_key.py\nmtllib key.mtl\no key\n')
    off = 0
    for cnt, (mat, verts, faces) in enumerate(objs):
        f.write(f'g part{cnt}\nusemtl {mat}\n')
        for v in verts:
            f.write('v %.5f %.5f %.5f\n' % v)
        for fc in faces:
            f.write('f ' + ' '.join(str(i + 1 + off) for i in fc) + '\n')
        off += len(verts)
print(len(objs), 'parts,', off, 'vertices')
