"""Shape helpers shared by generate_bob.py and generate_saucer.py (taken from
../mosquito/generate_mosquito.py): meshes with smooth normals written as `vn`, tubes along smooth
paths, ellipsoids, rotations."""
import math

import numpy as np


def unit(v):
    n = np.linalg.norm(v)
    return v / n if n > 1e-12 else v


class Mesh:
    def __init__(self):
        self.pieces = []  # (material, vertices, normals, faces)

    def add(self, mat, V, N, F):
        """Faces are turned, if need be, to agree with the normals (outwards by construction)."""
        V = np.asarray(V, float)
        N = np.asarray(N, float)
        agree = 0.0
        for f in F:
            fn = np.cross(V[f[1]] - V[f[0]], V[f[2]] - V[f[0]])
            agree += float(np.dot(fn, N[f[0]]))
        if agree < 0:
            F = [f[::-1] for f in F]
        self.pieces.append((mat, V, N, F))

    def write(self, name, mtl, title):
        total_v = 0
        with open(name, 'w') as f:
            f.write(f'# generated by a generate_*.py\nmtllib {mtl}\no {title}\n')
            off = 0
            for cnt, (mat, V, N, F) in enumerate(self.pieces):
                f.write(f'g part{cnt}\nusemtl {mat}\n')
                for v in V:
                    f.write('v %.5f %.5f %.5f\n' % tuple(v))
                for n in N:
                    f.write('vn %.4f %.4f %.4f\n' % tuple(n))
                for fc in F:
                    f.write('f ' + ' '.join(f'{i + 1 + off}//{i + 1 + off}' for i in fc) + '\n')
                off += len(V)
                total_v += len(V)
        allv = np.vstack([p[1] for p in self.pieces])
        print(name, len(self.pieces), 'parts,', total_v, 'vertices; bbox',
              allv.min(0).round(2), allv.max(0).round(2))


def write_mtl(name, mats):
    with open(name, 'w') as f:
        f.write('# generated by a generate_*.py\n')
        for n, (c, d) in mats.items():
            f.write(f'newmtl {n}\nKa {c[0]:.3f} {c[1]:.3f} {c[2]:.3f}\nKd {c[0]:.3f} {c[1]:.3f} {c[2]:.3f}\n'
                    f'Ks 0.30 0.30 0.30\nNs 40\nd {d:.2f}\nillum 2\n\n')


# ------------------------------------------------------------------------- shapes
def catmull(points, per_segment=6):
    P = [np.asarray(p, float) for p in points]
    if len(P) < 3:
        return [P[0] + (P[-1] - P[0]) * t for t in np.linspace(0, 1, per_segment + 1)]
    out = []
    ext = [2 * P[0] - P[1]] + P + [2 * P[-1] - P[-2]]
    for i in range(1, len(ext) - 2):
        p0, p1, p2, p3 = ext[i - 1], ext[i], ext[i + 1], ext[i + 2]
        for k in range(per_segment):
            t = k / per_segment
            out.append(0.5 * ((2 * p1) + (-p0 + p2) * t + (2 * p0 - 5 * p1 + 4 * p2 - p3) * t * t +
                              (-p0 + 3 * p1 - 3 * p2 + p3) * t ** 3))
    out.append(P[-1])
    return out


def grid_mesh(P, centres):
    nj, ni = P.shape[0], P.shape[1]
    N = np.zeros_like(P)
    for j in range(nj):
        for i in range(ni):
            du = P[j, (i + 1) % ni] - P[j, (i - 1) % ni]
            dv = P[min(j + 1, nj - 1), i] - P[max(j - 1, 0), i]
            n = np.cross(du, dv)
            out = P[j, i] - centres[j]
            if np.linalg.norm(n) < 1e-10:
                n = out
            if np.dot(n, out) < 0:
                n = -n
            N[j, i] = unit(n)
    F = []
    for j in range(nj - 1):
        for i in range(ni):
            a, b = j * ni + i, j * ni + (i + 1) % ni
            c, d = (j + 1) * ni + (i + 1) % ni, (j + 1) * ni + i
            F.append([a, b, c, d])
    return P.reshape(-1, 3), N.reshape(-1, 3), F


def tube(mesh, mat, ctrl, radii, seg=10, per_segment=5):
    """A tube along a smooth path through `ctrl`, its radius going through `radii`."""
    path = catmull(ctrl, per_segment)
    rad = [r[0] for r in catmull([[r] for r in radii], per_segment)]
    K = len(path)
    rings = np.zeros((K, seg, 3))
    u = None
    for k in range(K):
        t = unit(path[min(k + 1, K - 1)] - path[max(k - 1, 0)])
        if u is None:
            ref = np.array([0.0, 1.0, 0.0])
            if abs(np.dot(ref, t)) > 0.9:
                ref = np.array([0.0, 0.0, 1.0])
            u = unit(ref - t * np.dot(ref, t))
        else:
            u = unit(u - t * np.dot(u, t))
        v = np.cross(t, u)
        for i in range(seg):
            a = 2 * math.pi * i / seg
            rings[k, i] = path[k] + rad[k] * (math.cos(a) * u + math.sin(a) * v)
    V, N, F = grid_mesh(rings, path)
    V, N = list(V), list(N)
    for k, direction in ((0, -unit(path[1] - path[0])), (K - 1, unit(path[-1] - path[-2]))):
        base = len(V)
        for i in range(seg):
            V.append(rings[k, i])
            N.append(direction)
        V.append(path[k])
        N.append(direction)
        for i in range(seg):
            F.append([base + (i + 1) % seg, base + seg, base + i])
    mesh.add(mat, V, N, F)
    return path


def ellipsoid(mesh, mat, centre, radii, nlat=10, nlon=16, rot=None, shape=None):
    """An ellipsoid (pole to pole along Y), turned by `rot`; `shape` may move a unit-sphere point."""
    c = np.asarray(centre, float)
    r = np.asarray(radii, float)
    V, N, F = [], [], []
    for j in range(nlat + 1):
        th = math.pi * j / nlat
        for i in range(nlon):
            ph = 2 * math.pi * i / nlon
            p = np.array([math.sin(th) * math.sin(ph), math.cos(th), math.sin(th) * math.cos(ph)])
            if shape:
                p = shape(p)
            q = p * r
            n = unit(p / r)
            if rot is not None:
                q, n = rot @ q, rot @ n
            V.append(c + q)
            N.append(unit(n))
    for j in range(nlat):
        for i in range(nlon):
            a, b = j * nlon + i, j * nlon + (i + 1) % nlon
            F.append([a, b, (j + 1) * nlon + (i + 1) % nlon, (j + 1) * nlon + i])
    mesh.add(mat, V, N, F)


def rot_x(a):
    c, s = math.cos(a), math.sin(a)
    return np.array([[1, 0, 0], [0, c, -s], [0, s, c]])


def along(direction):
    """A rotation that takes +Y to `direction` (for ellipsoids lying along a path)."""
    d = unit(np.asarray(direction, float))
    y = np.array([0.0, 1.0, 0.0])
    v = np.cross(y, d)
    s, c = np.linalg.norm(v), float(np.dot(y, d))
    if s < 1e-9:
        return np.eye(3) if c > 0 else np.diag([1.0, -1.0, -1.0])
    k = np.array([[0, -v[2], v[1]], [v[2], 0, -v[0]], [-v[1], v[0], 0]])
    return np.eye(3) + k + k @ k * ((1 - c) / s ** 2)


def mirror(points):
    return [(-p[0], p[1], p[2]) for p in points]


