#!/usr/bin/env python3
"""Procedurally builds the shadow creature: a tall, hunched, slightly
deformed humanoid that is almost pure black, with glowing yellow eyes.

Outputs (next to this script):
  creature.obj / creature.jpg        body (near-black, lit by the scene lights)
  creature_eyes.obj / creature_eyes.jpg   eyes (draw these unlit / emissive)
  creature.mtl

The creature stands with its feet at y = 0, about 3.6 units tall (4.4 with the horn), facing +z.
Usage: python3 generate_creature.py   (needs numpy and Pillow)
"""
import os
import numpy as np
from PIL import Image

OUT = os.path.dirname(os.path.abspath(__file__))
rng = np.random.default_rng(666)


# ------------------------------------------------------------------ geometry
class Mesh:
    def __init__(self, material):
        self.material = material
        self.v, self.vt, self.f = [], [], []

    def add(self, p, uv=(0.0, 0.0)):
        self.v.append(np.array(p, dtype=float))
        self.vt.append(uv)
        return len(self.v) - 1

    def warp(self, fn):
        self.v = [fn(p) for p in self.v]

    def normals(self):
        v = np.array(self.v)
        n = np.zeros_like(v)
        for a, b, c in self.f:
            fn = np.cross(v[b] - v[a], v[c] - v[a])
            n[a] += fn
            n[b] += fn
            n[c] += fn
        keys = {}
        for i, p in enumerate(np.round(v, 4)):
            keys.setdefault(tuple(p), []).append(i)
        for idx in keys.values():       # share normals across UV seams
            n[idx] = n[idx].sum(axis=0)
        ln = np.linalg.norm(n, axis=1, keepdims=True)
        ln[ln == 0] = 1
        return n / ln

    def write(self, name):
        n = self.normals()
        with open(os.path.join(OUT, name), "w") as fh:
            fh.write("# generated by generate_creature.py\nmtllib creature.mtl\n")
            fh.write("o %s\n" % os.path.splitext(name)[0])
            for p in self.v:
                fh.write("v %.5f %.5f %.5f\n" % tuple(p))
            for t in self.vt:
                fh.write("vt %.5f %.5f\n" % tuple(t))
            for p in n:
                fh.write("vn %.5f %.5f %.5f\n" % tuple(p))
            fh.write("usemtl %s\ns 1\n" % self.material)
            for a, b, c in self.f:
                fh.write("f %d/%d/%d %d/%d/%d %d/%d/%d\n" %
                         (a + 1, a + 1, a + 1, b + 1, b + 1, b + 1, c + 1, c + 1, c + 1))


def spline(points, n):
    """Catmull-Rom curve through `points`, sampled at n points."""
    p = np.array(points, dtype=float)
    p = np.vstack([2 * p[0] - p[1], p, 2 * p[-1] - p[-2]])
    out = []
    segs = len(p) - 3
    for k in range(n):
        t = k / (n - 1) * segs
        i = min(int(t), segs - 1)
        u = t - i
        p0, p1, p2, p3 = p[i], p[i + 1], p[i + 2], p[i + 3]
        out.append(0.5 * ((2 * p1) + (-p0 + p2) * u +
                          (2 * p0 - 5 * p1 + 4 * p2 - p3) * u ** 2 +
                          (-p0 + 3 * p1 - 3 * p2 + p3) * u ** 3))
    return np.array(out)


def sweep(m, points, radii, n=24, sides=10, flat=1.0, lumps=0.0, tip=0.9, seed=0):
    """Tube along a spline. `radii` are interpolated along the path; `flat`
    squashes the section sideways (ribs/limbs), `lumps` adds irregular bumps,
    `tip` closes the end with a point `tip * radius` beyond the last ring
    (0 = flat cap)."""
    path = spline(points, n)
    r = np.interp(np.linspace(0, 1, n), np.linspace(0, 1, len(radii)), radii)
    tang = np.gradient(path, axis=0)
    tang /= np.linalg.norm(tang, axis=1, keepdims=True)
    ref = np.array([0.0, 0.0, 1.0]) if abs(tang[0][2]) < 0.9 else np.array([1.0, 0.0, 0.0])
    side = np.cross(tang[0], ref)
    side /= np.linalg.norm(side)
    ph = np.random.default_rng(seed).random(3) * 6
    rings = []
    length = 0.0
    for k in range(n):
        if k:
            length += np.linalg.norm(path[k] - path[k - 1])
        t = tang[k]
        side = side - t * np.dot(side, t)
        side /= np.linalg.norm(side)
        other = np.cross(t, side)
        ring = []
        for s in range(sides + 1):
            th = 2 * np.pi * s / sides
            bump = 1 + lumps * np.sin(3 * th + ph[0] + 2 * k) * np.sin(1.7 * k + ph[1]) \
                + 0.5 * lumps * np.sin(5 * th + ph[2] - k)
            rr = r[k] * bump
            p = path[k] + rr * (np.cos(th) * side * flat + np.sin(th) * other)
            ring.append(m.add(p, (s / sides, length * 0.3)))
        rings.append(ring)
    for k in range(n - 1):
        for s in range(sides):
            a, b = rings[k][s], rings[k][s + 1]
            c, d = rings[k + 1][s], rings[k + 1][s + 1]
            m.f += [(a, b, c), (b, d, c)]
    end = m.add(path[-1] + tang[-1] * r[-1] * tip, (0.5, length * 0.3))
    for s in range(sides):
        m.f.append((rings[-1][s], rings[-1][s + 1], end))
    start = m.add(path[0] - tang[0] * r[0] * 0.2, (0.5, 0.0))
    for s in range(sides):
        m.f.append((rings[0][s + 1], rings[0][s], start))


def ellipsoid(m, center, radii, rings=14, sides=20, tilt=(0.0, 0.0)):
    """Ellipsoid; tilt = (pitch, roll) in radians about x / z."""
    cx, cy, cz = center
    ids = []
    cp, sp = np.cos(tilt[0]), np.sin(tilt[0])
    cr, sr = np.cos(tilt[1]), np.sin(tilt[1])
    for j in range(rings + 1):
        phi = np.pi * j / rings
        row = []
        for i in range(sides + 1):
            th = 2 * np.pi * i / sides
            p = np.array([np.sin(phi) * np.cos(th) * radii[0],
                          np.cos(phi) * radii[1],
                          np.sin(phi) * np.sin(th) * radii[2]])
            p = np.array([p[0], p[1] * cp - p[2] * sp, p[1] * sp + p[2] * cp])
            p = np.array([p[0] * cr - p[1] * sr, p[0] * sr + p[1] * cr, p[2]])
            row.append(m.add(np.array([cx, cy, cz]) + p, (i / sides, j / rings)))
        ids.append(row)
    for j in range(rings):
        for i in range(sides):
            a, b, c, d = ids[j][i], ids[j][i + 1], ids[j + 1][i], ids[j + 1][i + 1]
            m.f += [(a, b, c), (b, d, c)]


def spike(m, base, direction, length, radius, sides=6, bend=(0, 0, 0)):
    """Curved thorn: a thin cone from `base` along `direction`."""
    d = np.array(direction, dtype=float)
    d /= np.linalg.norm(d)
    pts = [np.array(base) - d * radius * 0.5,
           np.array(base) + d * length * 0.5 + np.array(bend) * 0.4,
           np.array(base) + d * length + np.array(bend)]
    sweep(m, pts, [radius, radius * 0.45, radius * 0.05], n=8, sides=sides, tip=1.0)


# ------------------------------------------------------------------ creature
def body_deform(p):
    """Global asymmetric warp: a slight lean + twist so nothing is symmetric."""
    x, y, z = p
    h = np.clip(y / 3.6, 0, 1)
    x += 0.10 * np.sin(y * 1.3) + 0.12 * h ** 2          # leans / bends to one side
    z += 0.16 * h ** 1.5 + 0.05 * np.sin(y * 2.1 + 1.0)   # hunched forward
    ang = 0.12 * h                                        # twists towards the top
    c, s = np.cos(ang), np.sin(ang)
    x, z = x * c - z * s, x * s + z * c
    return np.array([x, y, z])


def build():
    body = Mesh("creature")
    eyes = Mesh("eyes")

    # Legs: digitigrade, too long, the left one a little longer than the right
    for side, extra in ((1, 0.0), (-1, 0.12)):
        sweep(body, [(0.20 * side, 1.78 + extra, 0.0), (0.30 * side, 1.15, 0.30),
                     (0.27 * side, 0.55, -0.10), (0.28 * side, 0.12, 0.10)],
              [0.14, 0.09, 0.055, 0.045], n=24, sides=8, lumps=0.08, tip=0.5,
              seed=3 + side)
        # Long clawed foot
        sweep(body, [(0.28 * side, 0.10, 0.05), (0.30 * side, 0.04, 0.35),
                     (0.31 * side, 0.0, 0.62)], [0.05, 0.035, 0.012], n=8, sides=6, tip=1.0)

    # Torso: narrow waist, big rib cage, tapering into the neck; bent forward
    sweep(body, [(0.0, 1.70, 0.0), (0.0, 2.10, 0.02), (0.05, 2.55, 0.12),
                 (0.12, 2.95, 0.30)],
          [0.20, 0.25, 0.34, 0.17], n=30, sides=14, flat=1.15, lumps=0.07, tip=0.4, seed=7)
    # Hump on the back
    ellipsoid(body, (-0.02, 2.80, -0.18), (0.26, 0.22, 0.26), tilt=(0.3, 0.2))
    # Pelvis
    ellipsoid(body, (0.0, 1.72, 0.0), (0.30, 0.16, 0.20))

    # Arms: very long, different lengths, claws dragging near the ground
    arms = {
        1:  [(0.42, 2.92, 0.25), (0.68, 2.05, 0.45), (0.62, 1.15, 0.62), (0.70, 0.45, 0.50)],
        -1: [(-0.40, 2.70, 0.22), (-0.78, 1.90, 0.40), (-0.88, 1.00, 0.70), (-0.66, 0.12, 0.62)],
    }
    for side, pts in arms.items():
        sweep(body, pts, [0.12, 0.075, 0.055, 0.045], n=26, sides=8, lumps=0.1,
              tip=0.5, seed=10 + side)
        wrist = np.array(pts[-1])
        for k, fx in enumerate((-0.07, 0.0, 0.07)):
            sweep(body, [wrist + np.array([fx, 0.0, 0.0]),
                         wrist + np.array([fx * 1.5, -0.20, 0.10]),
                         wrist + np.array([fx * 2.0, -0.40, 0.30 + 0.06 * k])],
                  [0.028, 0.02, 0.006], n=8, sides=5, tip=1.0)
    # Spines along the back, uneven and one broken
    for k in range(8):
        t = k / 7
        y = 1.95 + 1.0 * t
        z = -0.20 - 0.10 * np.sin(t * 3)
        length = (0.30 + 0.25 * rng.random()) * (0.4 if k == 5 else 1.0)
        spike(body, (0.03 * k - 0.1, y, z), (0.0, 0.5, -1.0), length, 0.05,
              bend=(0.0, 0.15, 0.0))
    # Shoulder thorns
    spike(body, (0.46, 3.02, 0.2), (0.6, 1.0, -0.2), 0.45, 0.06)
    spike(body, (-0.42, 2.85, 0.15), (-0.8, 0.8, 0.0), 0.28, 0.05)

    # Neck + elongated head, tilted to the side
    sweep(body, [(0.12, 2.92, 0.30), (0.17, 3.15, 0.50), (0.22, 3.32, 0.68)],
          [0.15, 0.10, 0.09], n=12, sides=10, tip=0.0, seed=21)
    head_c = np.array([0.24, 3.44, 0.83])
    ellipsoid(body, head_c, (0.17, 0.30, 0.22), tilt=(-0.45, 0.18))
    # Narrow jaw / snout
    ellipsoid(body, head_c + np.array([0.0, -0.17, 0.17]), (0.11, 0.12, 0.20), tilt=(-0.2, 0.1))
    # Horns: one long and curved back, one snapped off short
    spike(body, head_c + np.array([0.11, 0.24, -0.02]), (0.3, 1.0, -0.8), 0.85, 0.055,
          bend=(0.15, 0.1, -0.35))
    spike(body, head_c + np.array([-0.11, 0.22, -0.02]), (-0.6, 1.0, -0.3), 0.26, 0.05)

    # Eyes: two slanted slits, slightly unequal, set into the front of the head
    for side, size in ((1, 1.0), (-1, 0.82)):
        ellipsoid(eyes, head_c + np.array([0.095 * side, 0.07 - 0.015 * side, 0.205]),
                  (0.070 * size, 0.032 * size, 0.022 * size), rings=8, sides=14,
                  tilt=(0.1, -0.5 * side))

    body.warp(body_deform)
    eyes.warp(body_deform)
    return body, eyes


# ------------------------------------------------------------------ textures
def make_textures():
    n = 256
    # Near-black skin with a faint mottling so the shape still catches a little
    # moonlight; it reads as black in the scene.
    f = np.fft.fft2(rng.standard_normal((n, n)))
    fy, fx = np.fft.fftfreq(n)[:, None], np.fft.fftfreq(n)[None, :]
    r = np.sqrt(fx * fx + fy * fy)
    r[0, 0] = 1
    a = np.real(np.fft.ifft2(f / r ** 1.4))
    a = (a - a.min()) / (a.max() - a.min())
    v = 6 + 16 * a
    Image.fromarray(np.stack([v, v, v * 1.1], -1).astype(np.uint8)).save(
        os.path.join(OUT, "creature.jpg"), quality=95)

    # Eye: white-hot centre fading to saturated yellow-orange (looks like a glow)
    m = 128
    yy, xx = np.mgrid[0:m, 0:m] / (m - 1) * 2 - 1
    d = np.clip(np.sqrt(xx * xx + yy * yy), 0, 1)
    c = np.stack([np.full_like(d, 255), 255 - 70 * d ** 1.5, 60 - 60 * d ** 0.8 + 140 * (1 - d) ** 3], -1)
    Image.fromarray(np.clip(c, 0, 255).astype(np.uint8)).save(
        os.path.join(OUT, "creature_eyes.jpg"), quality=95)

    with open(os.path.join(OUT, "creature.mtl"), "w") as fh:
        fh.write("# generated by generate_creature.py\n"
                 "newmtl creature\nNs 8\nKa 1 1 1\nKd 1 1 1\nKs 0 0 0\nillum 1\nmap_Kd creature.jpg\n\n"
                 "newmtl eyes\nNs 1\nKa 1 1 1\nKd 1 1 1\nKs 0 0 0\nKe 1 0.9 0.2\nillum 1\nmap_Kd creature_eyes.jpg\n")


if __name__ == "__main__":
    body, eyes = build()
    body.write("creature.obj")
    eyes.write("creature_eyes.obj")
    make_textures()
    v = np.array(body.v)
    print("done; height %.2f, width %.2f" % (v[:, 1].max(), np.ptp(v[:, 0])))
