"""Generates the forest map's models: the floor and the pines.

- forest_floor.obj/.mtl + forest_floor.png: the ground, SIZE x SIZE metres centred on the origin
  (a grid of 1 m cells, y up), with gentle bumps (+-HILL m); the texture (needles, moss and earth)
  repeats every TILE metres.
- pine_0.obj .. pine_2.obj (+ pine.mtl): low-poly pines, faceted (no `vn`: the engine makes flat
  normals), standing on the origin, about PINE_HEIGHT metres tall: an 8-sided trunk and 5 stacked
  cones of foliage, each variant a little different. The crown starts at CROWN_BASE * height and
  its widest radius is CROWN_RADIUS * height: the engine draws the shadows of the crowns with the
  same numbers (ForestStage.cpp, CROWN_BASE and CROWN_RADIUS).

Meters, Y up, like the rest of the project. Needs numpy and Pillow. Fixed seed.
"""
import math

import numpy as np
from PIL import Image

rng = np.random.default_rng(31)

SIZE = 200.0
HILL = 1.2
TILE = 4.0
PINE_HEIGHT = 20.0
CROWN_BASE = 0.22
CROWN_RADIUS = 0.2
SIDES = 8


def floor_height(x, z):
    """Gentle bumps: a few broad sines, the same as the engine sees through the mesh."""
    return HILL * (0.5 * math.sin(x * 0.045 + 1.3) * math.cos(z * 0.038 - 0.7) +
                   0.3 * math.sin(x * 0.11 - z * 0.07 + 2.1) +
                   0.2 * math.cos(x * 0.021 + z * 0.093))


def write_floor():
    n = int(SIZE) + 1
    half = SIZE / 2
    with open('forest_floor.obj', 'w') as f:
        f.write('# generated by generate_forest.py\nmtllib forest_floor.mtl\no forest_floor\n')
        for j in range(n):
            for i in range(n):
                x, z = -half + i, -half + j
                f.write(f'v {x:.3f} {floor_height(x, z):.4f} {z:.3f}\n')
        for j in range(n):
            for i in range(n):
                f.write(f'vt {i / TILE:.4f} {j / TILE:.4f}\n')
        f.write('usemtl ground\n')
        for j in range(n - 1):
            for i in range(n - 1):
                a = j * n + i + 1
                b, c, d = a + 1, a + n + 1, a + n
                # counter-clockwise seen from above (+y): the normal points up
                f.write(f'f {a}/{a} {d}/{d} {c}/{c} {b}/{b}\n')
    with open('forest_floor.mtl', 'w') as f:
        f.write('# generated by generate_forest.py\nnewmtl ground\nKa 1 1 1\nKd 1 1 1\n'
                'Ks 0.05 0.05 0.05\nNs 8\nillum 2\nmap_Kd forest_floor.png\n')
    # the texture: brown earth, patches of moss, fallen needles (short dark strokes)
    s = 512
    yy, xx = np.mgrid[0:s, 0:s] / s

    def tile_noise(freq, seed):
        r = np.random.default_rng(seed)
        g = r.random((freq, freq))
        # bilinear, wrapping, so that the texture tiles
        fx, fy = xx * freq, yy * freq
        x0, y0 = np.floor(fx).astype(int), np.floor(fy).astype(int)
        tx, ty = fx - x0, fy - y0
        tx, ty = tx * tx * (3 - 2 * tx), ty * ty * (3 - 2 * ty)
        x1, y1 = (x0 + 1) % freq, (y0 + 1) % freq
        x0, y0 = x0 % freq, y0 % freq
        return (g[y0, x0] * (1 - tx) * (1 - ty) + g[y0, x1] * tx * (1 - ty) +
                g[y1, x0] * (1 - tx) * ty + g[y1, x1] * tx * ty)

    moss = tile_noise(6, 1) * 0.6 + tile_noise(17, 2) * 0.4
    grain = tile_noise(64, 3) * 0.5 + tile_noise(128, 4) * 0.5
    earth = np.array([0.33, 0.25, 0.16])
    green = np.array([0.24, 0.32, 0.13])
    m = np.clip((moss - 0.45) * 3.0, 0, 1)[..., None]
    img = earth * (1 - m) + green * m
    img = img * (0.8 + 0.4 * grain[..., None])
    needles = Image.fromarray((np.clip(img, 0, 1) * 255).astype(np.uint8))
    px = needles.load()
    for _ in range(2600):  # fallen needles: short strokes, reddish brown, wrapping round the edges
        x0, y0 = rng.integers(0, s, 2)
        a = rng.random() * math.pi
        c = tuple(int(v) for v in (np.array([0.45, 0.30, 0.17]) * (0.7 + 0.5 * rng.random()) * 255))
        for t in range(int(6 + rng.random() * 8)):
            px[int(x0 + t * math.cos(a)) % s, int(y0 + t * math.sin(a)) % s] = c
    needles.save('forest_floor.png')
    print('forest_floor.obj:', n * n, 'vertices; forest_floor.png', s, 'px')


def write_pines():
    with open('pine.mtl', 'w') as f:
        f.write('# generated by generate_forest.py\n')
        for name, c in (('bark', (0.30, 0.20, 0.13)), ('needles', (0.10, 0.24, 0.12)),
                        ('needles_dark', (0.07, 0.18, 0.10))):
            f.write(f'newmtl {name}\nKa {c[0]} {c[1]} {c[2]}\nKd {c[0]} {c[1]} {c[2]}\n'
                    'Ks 0.02 0.02 0.02\nNs 4\nillum 2\n\n')
    for variant in range(3):
        r = np.random.default_rng(100 + variant)
        h = PINE_HEIGHT * (0.9 + 0.2 * r.random())
        verts, faces = [], []  # faces: (material, [indices])

        def ring(y, radius, twist=0.0):
            start = len(verts)
            for k in range(SIDES):
                a = 2 * math.pi * k / SIDES + twist
                verts.append((radius * math.cos(a), y, radius * math.sin(a)))
            return start

        def apex(y):
            verts.append((0.0, y, 0.0))
            return len(verts) - 1

        # the trunk, up into the crown
        b = ring(0.0, 0.035 * h)
        t = ring(0.75 * h, 0.012 * h)
        for k in range(SIDES):
            k2 = (k + 1) % SIDES
            faces.append(('bark', [b + k, t + k, t + k2, b + k2]))
        # 5 stacked cones, overlapping, smaller and closer together towards the top
        tiers = 5
        base = CROWN_BASE * h
        for i in range(tiers):
            f0 = i / tiers
            y0 = base + (h - base) * (f0 ** 1.15) * 0.92
            y1 = min(h, y0 + (h - base) * (0.42 - 0.18 * f0))
            if i == tiers - 1:
                y1 = h
            rad = CROWN_RADIUS * h * (1.0 - 0.8 * f0) * (0.9 + 0.2 * r.random())
            mat = 'needles' if i % 2 == 0 else 'needles_dark'
            rb = ring(y0, rad, twist=r.random())
            # the underside: a flat fan, so the cone is closed
            c0 = apex(y0 + 0.05 * (y1 - y0))
            top = apex(y1)
            for k in range(SIDES):
                k2 = (k + 1) % SIDES
                faces.append((mat, [rb + k, top, rb + k2]))
                faces.append((mat, [rb + k2, c0, rb + k]))
        name = f'pine_{variant}.obj'
        with open(name, 'w') as f:
            f.write(f'# generated by generate_forest.py\nmtllib pine.mtl\no pine_{variant}\n')
            for v in verts:
                f.write('v %.4f %.4f %.4f\n' % v)
            for mat in ('bark', 'needles', 'needles_dark'):
                f.write(f'usemtl {mat}\n')
                for m, idx in faces:
                    if m == mat:
                        f.write('f ' + ' '.join(str(i + 1) for i in idx) + '\n')
        print(name, len(verts), 'vertices,', len(faces), 'faces, height %.1f m' % h)


write_floor()
write_pines()
