#!/usr/bin/env python3
"""Generates the unit cube used by the Satellite (OBJ + MTL + JPG atlas).

Usage: python3 generate_cube.py        (writes next to this script)
Needs Pillow.

The cube is centred at the origin with side 1. The texture is a 3x2 atlas,
one tile per face. The +y face is the boresight, the direction the satellite
points at: an orange target, so the orientation can be read at a glance.
The other faces are grey panels.
"""
import os
from PIL import Image, ImageDraw

OUT = os.path.dirname(os.path.abspath(__file__))
TILE = 128

# face name -> (atlas column, atlas row), row 0 at the top of the image
TILES = {'+y': (0, 0), '-y': (1, 0), '+x': (2, 0),
         '-x': (0, 1), '+z': (1, 1), '-z': (2, 1)}


def panel(draw, x0, y0, base):
    draw.rectangle([x0, y0, x0 + TILE - 1, y0 + TILE - 1], fill=base)
    draw.rectangle([x0 + 6, y0 + 6, x0 + TILE - 7, y0 + TILE - 7],
                   outline=(60, 62, 70), width=4)
    for i in range(1, 4):  # solar-panel like grid
        x = x0 + 6 + i * (TILE - 12) // 4
        y = y0 + 6 + i * (TILE - 12) // 4
        draw.line([x, y0 + 8, x, y0 + TILE - 9], fill=(95, 100, 112), width=2)
        draw.line([x0 + 8, y, x0 + TILE - 9, y], fill=(95, 100, 112), width=2)


def boresight(draw, x0, y0):
    c = (x0 + TILE // 2, y0 + TILE // 2)
    draw.rectangle([x0, y0, x0 + TILE - 1, y0 + TILE - 1], fill=(235, 120, 30))
    for r, colour in ((52, (40, 30, 25)), (40, (250, 200, 120)),
                      (26, (40, 30, 25)), (14, (250, 200, 120))):
        draw.ellipse([c[0] - r, c[1] - r, c[0] + r, c[1] + r], fill=colour)
    draw.line([c[0], y0 + 4, c[0], y0 + TILE - 5], fill=(40, 30, 25), width=3)
    draw.line([x0 + 4, c[1], x0 + TILE - 5, c[1]], fill=(40, 30, 25), width=3)


def make_texture():
    img = Image.new('RGB', (3 * TILE, 2 * TILE))
    draw = ImageDraw.Draw(img)
    for face, (col, row) in TILES.items():
        x0, y0 = col * TILE, row * TILE
        if face == '+y':
            boresight(draw, x0, y0)
        else:
            panel(draw, x0, y0, (150, 155, 165) if face != '-y' else (70, 72, 80))
    img.save(os.path.join(OUT, 'cube.jpg'), quality=92)


# Corners of each face, counter-clockwise seen from outside, starting at the
# corner that maps to the bottom-left of its tile
FACES = {
    '+y': ((-1, 1, 1), (1, 1, 1), (1, 1, -1), (-1, 1, -1)),
    '-y': ((-1, -1, -1), (1, -1, -1), (1, -1, 1), (-1, -1, 1)),
    '+x': ((1, -1, 1), (1, -1, -1), (1, 1, -1), (1, 1, 1)),
    '-x': ((-1, -1, -1), (-1, -1, 1), (-1, 1, 1), (-1, 1, -1)),
    '+z': ((-1, -1, 1), (1, -1, 1), (1, 1, 1), (-1, 1, 1)),
    '-z': ((1, -1, -1), (-1, -1, -1), (-1, 1, -1), (1, 1, -1)),
}
NORMALS = {'+y': (0, 1, 0), '-y': (0, -1, 0), '+x': (1, 0, 0),
           '-x': (-1, 0, 0), '+z': (0, 0, 1), '-z': (0, 0, -1)}


def make_obj():
    lines = ['# generated by generate_cube.py', 'mtllib cube.mtl', 'o cube',
             'usemtl cube']
    faces = []
    for n, (face, corners) in enumerate(FACES.items()):
        col, row = TILES[face]
        # OBJ v goes up from the bottom of the image; inset half a texel
        u0, u1 = (col * TILE + 1) / (3 * TILE), ((col + 1) * TILE - 1) / (3 * TILE)
        v1 = 1 - (row * TILE + 1) / (2 * TILE)
        v0 = 1 - ((row + 1) * TILE - 1) / (2 * TILE)
        for x, y, z in corners:
            lines.append(f'v {x * 0.5} {y * 0.5} {z * 0.5}')
        for u, v in ((u0, v0), (u1, v0), (u1, v1), (u0, v1)):
            lines.append(f'vt {u:.5f} {v:.5f}')
        lines.append('vn %d %d %d' % NORMALS[face])
        b = 4 * n
        idx = [f'{b + k + 1}/{b + k + 1}/{n + 1}' for k in range(4)]
        faces.append(f'f {idx[0]} {idx[1]} {idx[2]}')
        faces.append(f'f {idx[0]} {idx[2]} {idx[3]}')
    with open(os.path.join(OUT, 'cube.obj'), 'w') as f:
        f.write('\n'.join(lines + faces) + '\n')
    with open(os.path.join(OUT, 'cube.mtl'), 'w') as f:
        f.write('# generated by generate_cube.py\nnewmtl cube\nNs 20\nKa 1 1 1\n'
                'Kd 1 1 1\nKs 0 0 0\nillum 1\nmap_Kd cube.jpg\n')


if __name__ == '__main__':
    make_texture()
    make_obj()
