"""Generates the giant mosquito: mosquito.obj/.mtl (the head and thorax), mosquito_abdomen.obj,
mosquito_wing_l.obj / mosquito_wing_r.obj (+ mosquito_wing.mtl) and the 24 segments of its legs
(mosquito_leg_<L|R><pair>_<segment>.obj): the abdomen, the wings and the legs apart so that the
engine can move them. Also its egg (mosquito_egg.obj/.mtl).

A tiger mosquito the size of a horse: black with white bands on the legs and the abdomen and white
marks on the back, big dark red eyes, a long proboscis curving down in front, feathery antennae,
six long thin legs hanging from the thorax (the hind pair curled up and back, as mosquitoes do) and
two long translucent wings with dark veins.

Meters, Y up, facing +Z (like the rest of the project). The origin is the middle of the thorax:
the object's position is where it flies. 3.4 m from the proboscis to the end of the abdomen, the
legs hang 1.7 m below the origin.

Each wing has its own frame: the origin is its hinge on the thorax, the left wing (the mosquito's
left, +X) spreads along +X and lies in the XZ plane (flat, its upper face +Y); the right one is
its mirror image. They go at WING_HINGE (and its mirror) on the body: the engine has the same
numbers (Mosquito.cpp, WING_HINGE_*).

Built like generate_folla_culos.py (tubes along smooth paths, ellipsoids, smooth normals written
as `vn`). Needs numpy. Fixed seed.
"""
import math
import random

import numpy as np

random.seed(7)

WING_HINGE = (0.20, 0.27, 0.10)  # left wing; the right one at (-x, y, z)
WING_SPAN = 1.65
WING_CHORD = 0.40

MATS = {  # name: (colour, opacity)
    'body': ((0.075, 0.07, 0.07), 1.0),
    'stripe': ((0.80, 0.80, 0.76), 1.0),
    'belly': ((0.32, 0.05, 0.04), 1.0),  # the abdomen's underside: dark red, full of blood
    'eye': ((0.30, 0.03, 0.03), 1.0),
    'proboscis': ((0.05, 0.045, 0.04), 1.0),
}
WING_MATS = {
    'wing': ((0.55, 0.60, 0.66), 0.38),
    'vein': ((0.10, 0.09, 0.08), 1.0),
}


def unit(v):
    n = np.linalg.norm(v)
    return v / n if n > 1e-12 else v


class Mesh:
    def __init__(self):
        self.pieces = []  # (material, vertices, normals, faces)

    def add(self, mat, V, N, F):
        """Faces are turned, if need be, to agree with the normals (outwards by construction)."""
        V = np.asarray(V, float)
        N = np.asarray(N, float)
        agree = 0.0
        for f in F:
            fn = np.cross(V[f[1]] - V[f[0]], V[f[2]] - V[f[0]])
            agree += float(np.dot(fn, N[f[0]]))
        if agree < 0:
            F = [f[::-1] for f in F]
        self.pieces.append((mat, V, N, F))

    def write(self, name, mtl, title):
        total_v = 0
        with open(name, 'w') as f:
            f.write(f'# generated by generate_mosquito.py\nmtllib {mtl}\no {title}\n')
            off = 0
            for cnt, (mat, V, N, F) in enumerate(self.pieces):
                f.write(f'g part{cnt}\nusemtl {mat}\n')
                for v in V:
                    f.write('v %.5f %.5f %.5f\n' % tuple(v))
                for n in N:
                    f.write('vn %.4f %.4f %.4f\n' % tuple(n))
                for fc in F:
                    f.write('f ' + ' '.join(f'{i + 1 + off}//{i + 1 + off}' for i in fc) + '\n')
                off += len(V)
                total_v += len(V)
        allv = np.vstack([p[1] for p in self.pieces])
        print(name, len(self.pieces), 'parts,', total_v, 'vertices; bbox',
              allv.min(0).round(2), allv.max(0).round(2))


def write_mtl(name, mats):
    with open(name, 'w') as f:
        f.write('# generated by generate_mosquito.py\n')
        for n, (c, d) in mats.items():
            f.write(f'newmtl {n}\nKa {c[0]:.3f} {c[1]:.3f} {c[2]:.3f}\nKd {c[0]:.3f} {c[1]:.3f} {c[2]:.3f}\n'
                    f'Ks 0.30 0.30 0.30\nNs 40\nd {d:.2f}\nillum 2\n\n')


# ------------------------------------------------------------------------- shapes
def catmull(points, per_segment=6):
    P = [np.asarray(p, float) for p in points]
    if len(P) < 3:
        return [P[0] + (P[-1] - P[0]) * t for t in np.linspace(0, 1, per_segment + 1)]
    out = []
    ext = [2 * P[0] - P[1]] + P + [2 * P[-1] - P[-2]]
    for i in range(1, len(ext) - 2):
        p0, p1, p2, p3 = ext[i - 1], ext[i], ext[i + 1], ext[i + 2]
        for k in range(per_segment):
            t = k / per_segment
            out.append(0.5 * ((2 * p1) + (-p0 + p2) * t + (2 * p0 - 5 * p1 + 4 * p2 - p3) * t * t +
                              (-p0 + 3 * p1 - 3 * p2 + p3) * t ** 3))
    out.append(P[-1])
    return out


def grid_mesh(P, centres):
    nj, ni = P.shape[0], P.shape[1]
    N = np.zeros_like(P)
    for j in range(nj):
        for i in range(ni):
            du = P[j, (i + 1) % ni] - P[j, (i - 1) % ni]
            dv = P[min(j + 1, nj - 1), i] - P[max(j - 1, 0), i]
            n = np.cross(du, dv)
            out = P[j, i] - centres[j]
            if np.linalg.norm(n) < 1e-10:
                n = out
            if np.dot(n, out) < 0:
                n = -n
            N[j, i] = unit(n)
    F = []
    for j in range(nj - 1):
        for i in range(ni):
            a, b = j * ni + i, j * ni + (i + 1) % ni
            c, d = (j + 1) * ni + (i + 1) % ni, (j + 1) * ni + i
            F.append([a, b, c, d])
    return P.reshape(-1, 3), N.reshape(-1, 3), F


def tube(mesh, mat, ctrl, radii, seg=10, per_segment=5):
    """A tube along a smooth path through `ctrl`, its radius going through `radii`."""
    path = catmull(ctrl, per_segment)
    rad = [r[0] for r in catmull([[r] for r in radii], per_segment)]
    K = len(path)
    rings = np.zeros((K, seg, 3))
    u = None
    for k in range(K):
        t = unit(path[min(k + 1, K - 1)] - path[max(k - 1, 0)])
        if u is None:
            ref = np.array([0.0, 1.0, 0.0])
            if abs(np.dot(ref, t)) > 0.9:
                ref = np.array([0.0, 0.0, 1.0])
            u = unit(ref - t * np.dot(ref, t))
        else:
            u = unit(u - t * np.dot(u, t))
        v = np.cross(t, u)
        for i in range(seg):
            a = 2 * math.pi * i / seg
            rings[k, i] = path[k] + rad[k] * (math.cos(a) * u + math.sin(a) * v)
    V, N, F = grid_mesh(rings, path)
    V, N = list(V), list(N)
    for k, direction in ((0, -unit(path[1] - path[0])), (K - 1, unit(path[-1] - path[-2]))):
        base = len(V)
        for i in range(seg):
            V.append(rings[k, i])
            N.append(direction)
        V.append(path[k])
        N.append(direction)
        for i in range(seg):
            F.append([base + (i + 1) % seg, base + seg, base + i])
    mesh.add(mat, V, N, F)
    return path


def ellipsoid(mesh, mat, centre, radii, nlat=10, nlon=16, rot=None, shape=None):
    """An ellipsoid (pole to pole along Y), turned by `rot`; `shape` may move a unit-sphere point."""
    c = np.asarray(centre, float)
    r = np.asarray(radii, float)
    V, N, F = [], [], []
    for j in range(nlat + 1):
        th = math.pi * j / nlat
        for i in range(nlon):
            ph = 2 * math.pi * i / nlon
            p = np.array([math.sin(th) * math.sin(ph), math.cos(th), math.sin(th) * math.cos(ph)])
            if shape:
                p = shape(p)
            q = p * r
            n = unit(p / r)
            if rot is not None:
                q, n = rot @ q, rot @ n
            V.append(c + q)
            N.append(unit(n))
    for j in range(nlat):
        for i in range(nlon):
            a, b = j * nlon + i, j * nlon + (i + 1) % nlon
            F.append([a, b, (j + 1) * nlon + (i + 1) % nlon, (j + 1) * nlon + i])
    mesh.add(mat, V, N, F)


def rot_x(a):
    c, s = math.cos(a), math.sin(a)
    return np.array([[1, 0, 0], [0, c, -s], [0, s, c]])


def along(direction):
    """A rotation that takes +Y to `direction` (for ellipsoids lying along a path)."""
    d = unit(np.asarray(direction, float))
    y = np.array([0.0, 1.0, 0.0])
    v = np.cross(y, d)
    s, c = np.linalg.norm(v), float(np.dot(y, d))
    if s < 1e-9:
        return np.eye(3) if c > 0 else np.diag([1.0, -1.0, -1.0])
    k = np.array([[0, -v[2], v[1]], [v[2], 0, -v[0]], [-v[1], v[0], 0]])
    return np.eye(3) + k + k @ k * ((1 - c) / s ** 2)


def mirror(points):
    return [(-p[0], p[1], p[2]) for p in points]


# --------------------------------------------------------------------------- body
body = Mesh()

# The thorax: a hunched oval, higher at the back of the head
ellipsoid(body, 'body', (0, 0.02, 0.02), (0.30, 0.33, 0.42), nlat=14, nlon=20, rot=rot_x(math.pi / 2),
          shape=lambda p: p * np.array([1.0, 1.0, 1.0 + 0.18 * max(0.0, p[1])]))
# its white marks on the back (a line down the middle and two at the sides)
ellipsoid(body, 'stripe', (0, 0.30, 0.10), (0.035, 0.07, 0.30), rot=rot_x(math.pi / 2 - 0.35))
for s in (1, -1):
    ellipsoid(body, 'stripe', (0.17 * s, 0.23, 0.18), (0.05, 0.05, 0.11), rot=rot_x(math.pi / 2 - 0.5))
    ellipsoid(body, 'stripe', (0.23 * s, 0.05, -0.12), (0.06, 0.12, 0.05))

# The head: low in front of the thorax, almost all eyes
ellipsoid(body, 'body', (0, -0.10, 0.50), (0.17, 0.17, 0.16), nlat=10, nlon=16)
for s in (1, -1):
    ellipsoid(body, 'eye', (0.105 * s, -0.07, 0.55), (0.10, 0.15, 0.12), nlat=10, nlon=14)
# the proboscis, long and thin, curving down; the palps beside it
tube(body, 'proboscis', [(0, -0.20, 0.62), (0, -0.33, 0.95), (0, -0.55, 1.30), (0, -0.82, 1.58),
                         (0, -1.05, 1.70)], [0.035, 0.028, 0.022, 0.016, 0.006], seg=8)
for s in (1, -1):
    tube(body, 'body', [(0.04 * s, -0.19, 0.62), (0.07 * s, -0.30, 0.82), (0.08 * s, -0.44, 0.95)],
         [0.022, 0.018, 0.012], seg=6)
    ellipsoid(body, 'stripe', (0.08 * s, -0.44, 0.95), (0.018, 0.018, 0.018), nlat=4, nlon=6)
# feathery antennae: a stalk with whorls of hairs
for s in (1, -1):
    stalk = tube(body, 'body', [(0.05 * s, 0.0, 0.63), (0.13 * s, 0.14, 0.86), (0.22 * s, 0.30, 1.05)],
                 [0.014, 0.010, 0.005], seg=6, per_segment=6)
    for k in range(2, len(stalk) - 1, 2):
        p = stalk[k]
        t = unit(stalk[k + 1] - stalk[k - 1])
        u = unit(np.cross(t, [0, 1, 0]))
        w = np.cross(t, u)
        length = 0.10 * (1.0 - k / len(stalk)) + 0.03
        for i in range(6):
            a = 2 * math.pi * i / 6 + k
            d = math.cos(a) * u + math.sin(a) * w
            tube(body, 'body', [p, p + d * length], [0.004, 0.002], seg=4, per_segment=1)

# The abdomen: 8 segments down a curve that sags behind the thorax, each with a white band at
# its front and a dark red underside. A model of its own (mosquito_abdomen.obj, in the body's
# frame), so that the engine can swell it when it fills with fuel: about ABDOMEN_PIVOT, where it
# joins the thorax (Mosquito.cpp has the same numbers)
ABDOMEN_PIVOT = (0.0, -0.05, -0.30)
abdomen = Mesh()
spine = catmull([(0, -0.05, -0.30), (0, -0.16, -0.80), (0, -0.30, -1.30), (0, -0.40, -1.72)], 8)
seg_count = 8
for k in range(seg_count):
    t0, t1 = k / seg_count, (k + 1) / seg_count
    a = spine[int(t0 * (len(spine) - 1))]
    b = spine[int(t1 * (len(spine) - 1))]
    mid = (a + b) / 2
    length = np.linalg.norm(b - a)
    r = 0.25 * (1.0 - 0.62 * ((k + 0.5) / seg_count) ** 1.4)
    rot = along(b - a)
    ellipsoid(abdomen, 'body', mid, (r, length * 0.62, r * 0.88), nlat=8, nlon=16, rot=rot)
    ellipsoid(abdomen, 'belly', mid - rot @ np.array([0, 0, r * 0.25]), (r * 0.9, length * 0.55, r * 0.70),
              nlat=8, nlon=14, rot=rot)
    ellipsoid(abdomen, 'stripe', a + (b - a) * 0.12, (r * 1.02, length * 0.12, r * 0.90), nlat=6, nlon=16,
              rot=rot)

# Six long legs (left side; the right side mirrors them): from the underside of the thorax up
# to a high "knee", then down and out. Each leg is 4 straight segments between its 5 joints, and
# each segment is a model of its own (mosquito_leg_<L|R><pair>_<segment>.obj, at its place in the
# body's frame), so that the engine can move them (Mosquito.cpp, LEG_JOINTS: the same numbers).
# White bands at the joints and the feet; the body only has a socket where each leg starts.
LEGS = [  # joints (hip, ..., foot), radii
    ([(0.12, -0.22, 0.20), (0.40, -0.10, 0.52), (0.72, -0.55, 0.95), (0.82, -1.20, 1.22), (0.88, -1.68, 1.35)],
     [0.050, 0.040, 0.030, 0.020, 0.009]),
    ([(0.15, -0.26, 0.00), (0.62, 0.02, 0.05), (1.12, -0.52, 0.00), (1.32, -1.22, -0.10), (1.42, -1.70, -0.14)],
     [0.052, 0.042, 0.030, 0.020, 0.009]),
    ([(0.12, -0.22, -0.20), (0.48, 0.02, -0.52), (0.80, -0.30, -1.08), (0.90, 0.08, -1.58), (0.84, 0.52, -1.90)],
     [0.050, 0.040, 0.030, 0.020, 0.009]),
]
leg_meshes = {}
for pair, (points, radii) in enumerate(LEGS):
    for side_name, side in (('L', points), ('R', mirror(points))):
        ellipsoid(body, 'body', side[0], (0.07, 0.07, 0.07), nlat=6, nlon=10)  # the socket
        for k in range(4):
            mesh = Mesh()
            a, b = np.array(side[k], float), np.array(side[k + 1], float)
            tube(mesh, 'body', [a, b], [radii[k], radii[k + 1]], seg=8, per_segment=1)
            if k > 0:  # the white band of the joint it starts at
                ellipsoid(mesh, 'stripe', a, (radii[k] * 1.25, 0.045, radii[k] * 1.25), nlat=5, nlon=8,
                          rot=along(b - a))
            if k == 3:
                ellipsoid(mesh, 'stripe', b, (0.016, 0.016, 0.016), nlat=4, nlon=6)
            leg_meshes[f'mosquito_leg_{side_name}{pair}_{k}.obj'] = mesh

# The halteres: little knobbed stalks behind the wings
for s in (1, -1):
    tube(body, 'body', [(0.16 * s, 0.18, -0.22), (0.26 * s, 0.22, -0.30)], [0.012, 0.008], seg=5,
         per_segment=1)
    ellipsoid(body, 'stripe', (0.27 * s, 0.22, -0.31), (0.03, 0.03, 0.03), nlat=5, nlon=8)

write_mtl('mosquito.mtl', MATS)
body.write('mosquito.obj', 'mosquito.mtl', 'mosquito')
abdomen.write('mosquito_abdomen.obj', 'mosquito.mtl', 'mosquito_abdomen')

# An egg: a dark, elongated grain with a paler float at its middle (they float on the water),
# 0.22 m long for this mosquito, lying along z. Its origin is its middle, on the water's surface.
egg = Mesh()
ellipsoid(egg, 'egg', (0, 0.03, 0), (0.035, 0.11, 0.035), nlat=8, nlon=10, rot=rot_x(math.pi / 2))
ellipsoid(egg, 'egg_float', (0, 0.02, 0), (0.05, 0.03, 0.045), nlat=6, nlon=10)
write_mtl('mosquito_egg.mtl', {'egg': ((0.12, 0.10, 0.09), 1.0), 'egg_float': ((0.55, 0.52, 0.45), 1.0)})
egg.write('mosquito_egg.obj', 'mosquito_egg.mtl', 'mosquito_egg')
for name, mesh in leg_meshes.items():
    mesh.write(name, 'mosquito.mtl', name[:-4])


# -------------------------------------------------------------------------- wings
def wing_outline(n=40):
    """The left wing's outline in its plane (x out from the hinge, z forward): a long narrow
    blade, the leading edge straight and sweeping back, the trailing edge rounded."""
    pts = []
    for i in range(n + 1):  # the leading edge, root to tip
        x = WING_SPAN * i / n
        pts.append((x, 0.05 - 0.17 * (x / WING_SPAN) ** 1.5))
    for i in range(1, n):  # round the tip and back along the trailing edge
        x = WING_SPAN * (1 - i / n)
        f = x / WING_SPAN
        width = WING_CHORD * math.sqrt(max(0.0, 1 - f ** 2.2)) * (0.35 + 0.65 * min(1.0, f * 4))
        pts.append((x, 0.05 - 0.17 * f ** 1.5 - width - 0.02))
    return pts


def make_wing(sign):
    mesh = Mesh()
    outline = wing_outline()
    centre = np.mean(np.array(outline), axis=0)
    V = [np.array([sign * x, 0.0, z]) for x, z in outline] + [np.array([sign * centre[0], 0.0, centre[1]])]
    N = [np.array([0.0, 1.0, 0.0])] * len(V)
    c = len(V) - 1
    F = [[i, (i + 1) % c, c] for i in range(c)]
    mesh.add('wing', V, N, F)
    # the veins: the leading edge and four that fan out from the root
    lead = [(sign * x, 0.004, z) for x, z in outline[:41:10]]
    tube(mesh, 'vein', lead, [0.012, 0.010, 0.008, 0.006, 0.004], seg=5, per_segment=4)
    for k, (tip_x, tip_dz) in enumerate([(1.45, -0.10), (1.20, -0.22), (0.95, -0.28), (0.65, -0.26)]):
        f = tip_x / WING_SPAN
        z_tip = 0.05 - 0.17 * f ** 1.5 + tip_dz
        tube(mesh, 'vein', [(sign * 0.04, 0.004, 0.0), (sign * tip_x * 0.5, 0.004, z_tip * 0.5 - 0.03 * k),
                            (sign * tip_x, 0.004, z_tip)], [0.007, 0.005, 0.003], seg=4, per_segment=4)
    return mesh


write_mtl('mosquito_wing.mtl', WING_MATS)
make_wing(1).write('mosquito_wing_l.obj', 'mosquito_wing.mtl', 'wing_l')
make_wing(-1).write('mosquito_wing_r.obj', 'mosquito_wing.mtl', 'wing_r')
