#!/usr/bin/env python3
"""Procedurally generates the desert assets (OBJ + MTL + JPG textures).

Usage: python3 generate_assets.py        (writes next to this script)
Needs numpy and Pillow. Everything is seeded, so the output is reproducible.
"""
import os
import numpy as np
from PIL import Image

OUT = os.path.dirname(os.path.abspath(__file__))
TERRAIN_SIZE = 160.0   # dunes.obj covers [-80, 80] on x and z
TERRAIN_RES = 192      # quads per side
SAND_TILE = 5.0        # world units covered by one sand.jpg tile


# ------------------------------------------------------------------ textures
def periodic_noise(n, power, rng):
    """Tileable noise: white noise filtered with 1/f^power in Fourier space."""
    f = np.fft.fft2(rng.standard_normal((n, n)))
    fy = np.fft.fftfreq(n)[:, None]
    fx = np.fft.fftfreq(n)[None, :]
    r = np.sqrt(fx * fx + fy * fy)
    r[0, 0] = 1.0
    f = f / r ** power
    f[0, 0] = 0
    a = np.real(np.fft.ifft2(f))
    return (a - a.min()) / (a.max() - a.min())


def lerp_color(t, c0, c1):
    t = np.clip(t, 0, 1)[..., None]
    return np.array(c0) * (1 - t) + np.array(c1) * t


def save_jpg(arr, name):
    Image.fromarray(np.clip(arr, 0, 255).astype(np.uint8)).save(
        os.path.join(OUT, name), quality=92)


def make_sand(rng, n=1024):
    large = periodic_noise(n, 1.6, rng)
    fine = periodic_noise(n, 0.4, rng)
    # Wind ripples: sine bands warped by the large noise (integer frequency
    # keeps the texture tileable)
    y = np.arange(n)[:, None] / n
    x = np.arange(n)[None, :] / n
    ripple = 0.5 + 0.5 * np.sin(2 * np.pi * (10 * y + 10 * x * 0.0 + 2.0 * (large - 0.5)))
    t = 0.55 * large + 0.25 * ripple + 0.20 * fine
    col = lerp_color(t, (196, 154, 98), (238, 208, 150))
    grain = (periodic_noise(n, 0.0, rng) - 0.5) * 22
    save_jpg(col + grain[..., None], "sand.jpg")


def make_cactus(rng, n=256):
    u = np.arange(n)[None, :] / n          # around the trunk
    v = np.arange(n)[:, None] / n          # along the trunk
    ribs = 0.5 + 0.5 * np.cos(2 * np.pi * 8 * u + 0 * v)
    noise = periodic_noise(n, 1.2, rng)
    t = 0.55 * ribs + 0.45 * noise
    col = lerp_color(t, (34, 82, 44), (92, 150, 82))
    # Spines: pale dots along the rib crests
    spines = np.zeros((n, n))
    for rib in range(8):
        cx = int((rib + 0.5) / 8 * n - n / 16) % n
        for cy in range(0, n, 12):
            spines[cy % n, cx % n] = 1.0
    spines = np.minimum(1.0, spines + np.roll(spines, 1, 0) + np.roll(spines, 1, 1))
    col = col * (1 - spines[..., None]) + np.array([235, 226, 170]) * spines[..., None]
    save_jpg(col, "cactus.jpg")


def make_rock(rng, n=512):
    big = periodic_noise(n, 1.8, rng)
    fine = periodic_noise(n, 0.8, rng)
    y = np.arange(n)[:, None] / n
    strata = 0.5 + 0.5 * np.sin(2 * np.pi * (6 * y + 1.5 * (big - 0.5)))
    t = 0.45 * big + 0.30 * strata + 0.25 * fine
    col = lerp_color(t, (96, 78, 66), (176, 150, 124))
    save_jpg(col, "rock.jpg")


# ------------------------------------------------------------------- meshes
class Mesh:
    def __init__(self, material):
        self.material = material
        self.v, self.vt, self.f = [], [], []   # f: triples of vertex indices

    def add_vertex(self, p, uv):
        self.v.append(p)
        self.vt.append(uv)
        return len(self.v) - 1

    def normals(self):
        """Smooth normals; vertices at the same position (UV seams) share them."""
        v = np.array(self.v, dtype=float)
        n = np.zeros_like(v)
        for a, b, c in self.f:
            fn = np.cross(v[b] - v[a], v[c] - v[a])
            n[a] += fn
            n[b] += fn
            n[c] += fn
        keys = {}
        for i, p in enumerate(np.round(v, 5)):
            keys.setdefault(tuple(p), []).append(i)
        for idx in keys.values():
            s = n[idx].sum(axis=0)
            n[idx] = s
        ln = np.linalg.norm(n, axis=1, keepdims=True)
        ln[ln == 0] = 1
        return n / ln

    def write(self, name):
        v = np.array(self.v)
        n = self.normals()
        with open(os.path.join(OUT, name), "w") as fh:
            fh.write("# generated by generate_assets.py\nmtllib desert.mtl\n")
            fh.write("o %s\n" % os.path.splitext(name)[0])
            for p in v:
                fh.write("v %.5f %.5f %.5f\n" % tuple(p))
            for t in self.vt:
                fh.write("vt %.5f %.5f\n" % tuple(t))
            for p in n:
                fh.write("vn %.5f %.5f %.5f\n" % tuple(p))
            fh.write("usemtl %s\ns 1\n" % self.material)
            for a, b, c in self.f:
                fh.write("f %d/%d/%d %d/%d/%d %d/%d/%d\n" %
                         (a + 1, a + 1, a + 1, b + 1, b + 1, b + 1,
                          c + 1, c + 1, c + 1))


def write_mtl():
    mats = {"sand": ("sand.jpg", (1, 1, 1), 5),
            "cactus": ("cactus.jpg", (1, 1, 1), 20),
            "rock": ("rock.jpg", (1, 1, 1), 10)}
    with open(os.path.join(OUT, "desert.mtl"), "w") as fh:
        fh.write("# generated by generate_assets.py\n")
        for name, (tex, kd, ns) in mats.items():
            fh.write("newmtl %s\nNs %d\nKa 1 1 1\nKd %g %g %g\nKs 0 0 0\nillum 1\nmap_Kd %s\n\n"
                     % (name, ns, kd[0], kd[1], kd[2], tex))


def smoothstep(a, b, x):
    t = np.clip((x - a) / (b - a), 0, 1)
    return t * t * (3 - 2 * t)


def dune_height(x, z):
    """Height of the dunes (>= 0). Flat in a clearing around the origin so the
    penguin has a place to stand; rises into dunes further away."""
    # Domain warp so the crests meander
    wx = x + 6.0 * np.sin(z * 0.11 + 1.3)
    wz = z + 5.0 * np.sin(x * 0.09)
    d = (np.sin(wx * 0.12 + wz * 0.05) * 0.5 + 0.5) ** 2.0 * 3.2
    d += (np.sin(wz * 0.07 - wx * 0.10 + 2.0) * 0.5 + 0.5) ** 2.5 * 2.2
    d += 0.25 * np.sin(wx * 0.9 + wz * 0.35) * np.sin(wz * 0.6)      # ripples
    d = np.maximum(d, 0)
    r = np.sqrt(x * x + z * z)
    return d * smoothstep(5.0, 22.0, r)


def make_dunes():
    n = TERRAIN_RES
    m = Mesh("sand")
    xs = np.linspace(-TERRAIN_SIZE / 2, TERRAIN_SIZE / 2, n + 1)
    idx = np.zeros((n + 1, n + 1), dtype=int)
    for j, z in enumerate(xs):
        for i, x in enumerate(xs):
            idx[j, i] = m.add_vertex((x, float(dune_height(x, z)), z),
                                     (x / SAND_TILE, z / SAND_TILE))
    for j in range(n):
        for i in range(n):
            a, b, c, d = idx[j, i], idx[j, i + 1], idx[j + 1, i], idx[j + 1, i + 1]
            m.f.append((a, c, b))     # counter-clockwise seen from above (+y)
            m.f.append((b, c, d))
    m.write("dunes.obj")


def tube(m, path, radius_fn, sides=16, ribs=0, rib_depth=0.0, v_scale=1.0):
    """Sweeps a ribbed circle along `path` (N x 3), closing the end with a dome."""
    path = np.array(path, dtype=float)
    N = len(path)
    tang = np.gradient(path, axis=0)
    tang /= np.linalg.norm(tang, axis=1, keepdims=True)
    up = np.array([0.0, 0.0, 1.0]) if abs(tang[0][2]) < 0.9 else np.array([1.0, 0.0, 0.0])
    side = np.cross(tang[0], up)
    side /= np.linalg.norm(side)
    rings = []
    lengths = np.concatenate([[0], np.cumsum(np.linalg.norm(np.diff(path, axis=0), axis=1))])
    for k in range(N):
        t = tang[k]
        side = side - t * np.dot(side, t)       # parallel transport
        side /= np.linalg.norm(side)
        other = np.cross(t, side)
        r = radius_fn(k / (N - 1))
        ring = []
        for s in range(sides + 1):
            th = 2 * np.pi * s / sides
            rr = r * (1 + rib_depth * np.cos(ribs * th))
            p = path[k] + rr * (np.cos(th) * side + np.sin(th) * other)
            ring.append(m.add_vertex(tuple(p), (s / sides, lengths[k] * v_scale)))
        rings.append(ring)
    for k in range(N - 1):
        for s in range(sides):
            a, b = rings[k][s], rings[k][s + 1]
            c, d = rings[k + 1][s], rings[k + 1][s + 1]
            m.f.append((a, b, c))
            m.f.append((b, d, c))
    # Dome on the end
    tip = m.add_vertex(tuple(path[-1] + tang[-1] * radius_fn(1.0) * 0.8), (0.5, lengths[-1] * v_scale))
    for s in range(sides):
        m.f.append((rings[-1][s], rings[-1][s + 1], tip))
    return tang


def bezier(p0, p1, p2, p3, n):
    t = np.linspace(0, 1, n)[:, None]
    return ((1 - t) ** 3 * p0 + 3 * (1 - t) ** 2 * t * p1 +
            3 * (1 - t) * t ** 2 * p2 + t ** 3 * p3)


def make_cactus_mesh(name, seed, arms):
    rng = np.random.default_rng(seed)
    m = Mesh("cactus")
    height = 2.4 + 0.4 * rng.random()
    r0 = 0.19
    trunk = np.array([[0, y, 0] for y in np.linspace(-0.05, height, 14)])
    tube(m, trunk, lambda t: r0 * (1 - 0.15 * t ** 3), ribs=8, rib_depth=0.07, v_scale=0.6)
    for (side, y0, up) in arms:
        # Arm leaves the trunk horizontally, then turns up
        start = np.array([side * r0 * 0.5, y0, 0.0])
        out = np.array([side * (0.75 + 0.2 * rng.random()), y0 + 0.05, 0.0])
        top = np.array([out[0] + side * 0.1, y0 + up, 0.0])
        path = bezier(start, start + np.array([side * 0.5, 0, 0]),
                      out + np.array([0, -0.0, 0]) + np.array([side * 0.15, 0.1, 0]),
                      top, 16)
        tube(m, path, lambda t: 0.12 * (1 - 0.15 * t ** 3), sides=12, ribs=6,
             rib_depth=0.07, v_scale=0.6)
    m.write(name)


def make_rock_mesh(name, seed, size, squash):
    rng = np.random.default_rng(seed)
    m = Mesh("rock")
    rings, sides = 18, 28
    phase = rng.random((6, 3)) * 10
    freq = np.array([1.3, 2.1, 3.4, 5.0, 7.0, 9.5])
    amp = np.array([0.30, 0.18, 0.10, 0.05, 0.03, 0.015])

    def lump(p):
        s = 0.0
        for k in range(6):
            s += amp[k] * np.sin(freq[k] * (p[0] * 1.0 + phase[k, 0])) * \
                np.sin(freq[k] * (p[1] * 1.1 + phase[k, 1])) * \
                np.sin(freq[k] * (p[2] * 0.9 + phase[k, 2]))
        return 1 + s

    ids = []
    for j in range(rings + 1):
        phi = np.pi * j / rings
        row = []
        for i in range(sides + 1):
            th = 2 * np.pi * i / sides
            d = np.array([np.sin(phi) * np.cos(th), np.cos(phi), np.sin(phi) * np.sin(th)])
            p = d * lump(d) * size
            p[1] = max(p[1] * squash, -0.25 * size)     # flat-ish bottom
            p[1] += 0.25 * size                         # sit on y = 0
            row.append(m.add_vertex(tuple(p), (i / sides * 2, j / rings * 2)))
        ids.append(row)
    for j in range(rings):
        for i in range(sides):
            a, b = ids[j][i], ids[j][i + 1]
            c, d = ids[j + 1][i], ids[j + 1][i + 1]
            m.f.append((a, b, c))
            m.f.append((b, d, c))
    m.write(name)


if __name__ == "__main__":
    rng = np.random.default_rng(7)
    make_sand(rng)
    make_cactus(rng)
    make_rock(rng)
    write_mtl()
    make_dunes()
    make_cactus_mesh("cactus_a.obj", 1, [(1, 0.9, 0.9), (-1, 1.5, 0.7)])
    make_cactus_mesh("cactus_b.obj", 2, [(-1, 1.1, 1.0)])
    make_rock_mesh("rock_a.obj", 3, 0.6, 0.6)
    make_rock_mesh("rock_b.obj", 4, 0.35, 0.8)
    print("done")
