"""Generates the shades (night monsters made of darkness: Shade.cpp). Feet on y = 0, facing +Z, metres.

Eight of them, all black or nearly (each in its own dark tone), all with tatters of darkness
hanging from them (thin tendrils, as if they were coming apart into smoke):
  shade_0.obj  wolf          (an animal: long and gaunt, 1.4 m at the head)
  shade_1.obj  stag          (an animal: very long thin legs, big antlers; 3 m with them)
  shade_2.obj  big cat       (an animal: low, crouched, a long tail curled up)
  shade_3.obj  crawler       (in between: a man on all fours, arms too long, elbows up)
  shade_4.obj  tall one      (a man: 2.5 m, thin, arms down to the knees, a small head)
  shade_5.obj  hunched one   (a man: a huge hunched back, arms that drag, a low head)
  shade_6.obj  goat man      (in between: a goat's head and horns on a man, legs bent like a goat's)
  shade_7.obj  crow man      (in between: a beak, ragged wings for arms, bird legs)
(+ shades.mtl). Needs numpy. Fixed seed. Shade.cpp keeps VARIANTS = 8.
"""
import math
import sys

import numpy as np

sys.path.insert(0, '.')
from shapes import Mesh, along, ellipsoid, rot_x, tube  # noqa: E402

# Dark, a little different each (nearly no shine: they swallow the light)
MATS = {
    'black': (0.012, 0.012, 0.014),
    'violet': (0.030, 0.016, 0.040),
    'moss': (0.020, 0.027, 0.016),
    'rust': (0.040, 0.018, 0.014),
    'slate': (0.024, 0.028, 0.036),
    'bone': (0.050, 0.045, 0.040),  # (antlers, horns, beak, claws: only a little less dark)
}

rng = np.random.default_rng(1977)


def write_mtl(name):
    with open(name, 'w') as f:
        f.write('# generated by generate_shades.py\n')
        for n, c in MATS.items():
            f.write(f'newmtl {n}\nKa {c[0]:.3f} {c[1]:.3f} {c[2]:.3f}\nKd {c[0]:.3f} {c[1]:.3f} {c[2]:.3f}\n'
                    f'Ks 0.05 0.05 0.05\nNs 12\nd 1.00\nillum 2\n\n')


def lumpy(amount, seed):
    """A shape for ellipsoid(): the surface goes in and out a little (not smooth: made of something)."""
    a, b, c = 3.0 + seed, 4.0 + 0.7 * seed, 5.0 + 0.3 * seed

    def f(p):
        k = 1.0 + amount * math.sin(a * p[0] + seed) * math.sin(b * p[1] + 2 * seed) * math.sin(c * p[2] + 1)
        return p * k
    return f


def blob(m, mat, centre, radii, amount=0.08, rot=None, nlat=12, nlon=18):
    ellipsoid(m, mat, centre, radii, nlat=nlat, nlon=nlon, rot=rot, shape=lumpy(amount, rng.uniform(0, 3)))


def limb(m, mat, pts, radii, seg=9):
    tube(m, mat, pts, radii, seg=seg, per_segment=4)


def both(f):
    """Calls f(s) for the right (s = -1) and the left (s = +1) side."""
    for s in (-1.0, 1.0):
        f(s)


def wisps(m, mat, anchors, length=(0.3, 0.7), radius=0.025):
    """Tatters of darkness hanging from the anchors, swaying a little."""
    for a in anchors:
        a = np.asarray(a, float)
        L = rng.uniform(*length)
        drift = rng.normal(0, 0.08, 3)
        drift[1] = 0
        pts = [a, a + np.array([0, -0.35 * L, 0]) + 0.4 * drift, a + np.array([0, -0.7 * L, 0]) + drift,
               a + np.array([0, -L, 0]) + 1.4 * drift]
        pts = [np.array([p[0], max(p[1], 0.05), p[2]]) for p in pts]
        r = radius * rng.uniform(0.7, 1.3)
        tube(m, mat, pts, [r, 0.75 * r, 0.4 * r, 0.05 * r], seg=6, per_segment=3)


def spikes(m, mat, base_pts, up=(0, 1, 0), length=0.12, radius=0.03):
    for p in base_pts:
        p = np.asarray(p, float)
        d = np.asarray(up, float) + rng.normal(0, 0.25, 3)
        d = d / np.linalg.norm(d)
        L = length * rng.uniform(0.7, 1.3)
        tube(m, mat, [p, p + d * L * 0.5, p + d * L], [radius, radius * 0.5, radius * 0.05], seg=6, per_segment=2)


models = []

# ------------------------------------------------------------------------ 0: wolf
m = Mesh()
c = 'black'
blob(m, c, (0, 0.80, 0.36), (0.26, 0.32, 0.32))
blob(m, c, (0, 0.77, 0.0), (0.22, 0.25, 0.55))
blob(m, c, (0, 0.78, -0.42), (0.21, 0.23, 0.25))
limb(m, c, [(0, 0.92, 0.52), (0, 1.02, 0.72), (0, 1.08, 0.86)], [0.17, 0.14, 0.12])
blob(m, c, (0, 1.10, 0.93), (0.15, 0.14, 0.17), amount=0.05)
limb(m, c, [(0, 1.08, 1.02), (0, 1.03, 1.24)], [0.09, 0.045])
both(lambda s: limb(m, c, [(0.08 * s, 1.20, 0.88), (0.12 * s, 1.37, 0.83)], [0.05, 0.004], seg=6))
both(lambda s: limb(m, c, [(0.13 * s, 0.78, 0.42), (0.15 * s, 0.45, 0.48), (0.14 * s, 0.20, 0.44),
                           (0.14 * s, 0.03, 0.50)], [0.10, 0.065, 0.05, 0.045]))
both(lambda s: limb(m, c, [(0.13 * s, 0.80, -0.45), (0.16 * s, 0.50, -0.32), (0.15 * s, 0.25, -0.55),
                           (0.14 * s, 0.03, -0.50)], [0.13, 0.08, 0.05, 0.045]))
both(lambda s: ellipsoid(m, c, (0.14 * s, 0.03, 0.54), (0.06, 0.03, 0.08), nlat=6, nlon=8))
both(lambda s: ellipsoid(m, c, (0.14 * s, 0.03, -0.46), (0.06, 0.03, 0.08), nlat=6, nlon=8))
limb(m, c, [(0, 0.85, -0.62), (0, 0.75, -0.95), (0, 0.52, -1.15), (0, 0.36, -1.26)], [0.07, 0.06, 0.04, 0.005])
spikes(m, c, [(0, 1.0 + 0.05 * math.cos(z * 2), z) for z in np.linspace(-0.45, 0.6, 9)], length=0.14)
wisps(m, c, [(x, 0.55, z) for x in (-0.12, 0.12) for z in np.linspace(-0.4, 0.4, 4)], length=(0.2, 0.4))
models.append(m)

# ------------------------------------------------------------------------ 1: stag
m = Mesh()
c, b = 'rust', 'bone'
blob(m, c, (0, 1.36, 0.0), (0.24, 0.30, 0.60))
blob(m, c, (0, 1.40, 0.36), (0.26, 0.32, 0.28))
both(lambda s: limb(m, c, [(0.14 * s, 1.30, 0.42), (0.15 * s, 0.85, 0.46), (0.13 * s, 0.45, 0.40),
                           (0.13 * s, 0.03, 0.45)], [0.09, 0.05, 0.035, 0.03]))
both(lambda s: limb(m, c, [(0.14 * s, 1.35, -0.42), (0.16 * s, 0.95, -0.34), (0.14 * s, 0.55, -0.60),
                           (0.13 * s, 0.03, -0.52)], [0.11, 0.06, 0.035, 0.03]))
limb(m, c, [(0, 1.52, 0.45), (0, 1.85, 0.62), (0, 2.05, 0.68)], [0.15, 0.10, 0.08])
blob(m, c, (0, 2.10, 0.74), (0.09, 0.10, 0.13), amount=0.04)
limb(m, c, [(0, 2.07, 0.82), (0, 1.98, 0.99)], [0.07, 0.035])
both(lambda s: limb(m, c, [(0.07 * s, 2.15, 0.70), (0.20 * s, 2.20, 0.66)], [0.035, 0.004], seg=6))


def antler(s):
    beam = [np.array(p) for p in [(0.04 * s, 2.18, 0.72), (0.24 * s, 2.45, 0.62), (0.40 * s, 2.72, 0.55),
                                  (0.50 * s, 3.00, 0.62)]]
    tube(m, b, beam, [0.035, 0.028, 0.02, 0.006], seg=7, per_segment=4)
    for i, (k, d) in enumerate([(0.15, (0.1 * s, 0.6, 1.0)), (0.45, (0.2 * s, 1.0, 0.6)),
                                (0.7, (0.0, 1.0, 0.1)), (0.85, (0.4 * s, 0.8, -0.3))]):
        p = beam[0] + (beam[-1] - beam[0]) * k + np.array([0.04 * s * math.sin(k * 6), 0, 0])
        dd = np.asarray(d) / np.linalg.norm(d)
        L = 0.22 + 0.06 * i
        tube(m, b, [p, p + dd * L * 0.6 + np.array([0, 0.03, 0]), p + dd * L], [0.02, 0.012, 0.003], seg=6,
             per_segment=2)


both(antler)
limb(m, c, [(0, 1.45, -0.58), (0, 1.38, -0.72)], [0.06, 0.01])
wisps(m, c, [(x, 1.12, z) for x in (-0.13, 0.0, 0.13) for z in np.linspace(-0.4, 0.45, 4)], length=(0.3, 0.7))
wisps(m, c, [(0, 1.75 - 0.2 * k, 0.58 + 0.06 * k) for k in range(3)], length=(0.3, 0.5), radius=0.02)
models.append(m)

# ------------------------------------------------------------------------ 2: big cat
m = Mesh()
c = 'moss'
blob(m, c, (0, 0.58, 0.0), (0.22, 0.21, 0.70))
blob(m, c, (0, 0.70, 0.42), (0.24, 0.24, 0.25))
blob(m, c, (0, 0.74, 0.88), (0.16, 0.13, 0.15), amount=0.04)
blob(m, c, (0, 0.69, 1.01), (0.09, 0.07, 0.08), amount=0.03)
limb(m, c, [(0, 0.74, 0.55), (0, 0.76, 0.78)], [0.15, 0.13])
both(lambda s: limb(m, c, [(0.10 * s, 0.84, 0.84), (0.12 * s, 0.93, 0.82)], [0.045, 0.006], seg=6))
both(lambda s: limb(m, c, [(0.15 * s, 0.65, 0.45), (0.17 * s, 0.35, 0.60), (0.15 * s, 0.04, 0.63)],
                   [0.10, 0.07, 0.06]))
both(lambda s: limb(m, c, [(0.15 * s, 0.62, -0.45), (0.18 * s, 0.42, -0.20), (0.15 * s, 0.16, -0.55),
                           (0.15 * s, 0.04, -0.45)], [0.13, 0.08, 0.06, 0.06]))
both(lambda s: ellipsoid(m, c, (0.15 * s, 0.035, 0.68), (0.07, 0.035, 0.09), nlat=6, nlon=8))
both(lambda s: ellipsoid(m, c, (0.15 * s, 0.035, -0.40), (0.07, 0.035, 0.09), nlat=6, nlon=8))
limb(m, c, [(0, 0.64, -0.68), (0, 0.50, -1.10), (0, 0.60, -1.50), (0, 0.90, -1.66), (0, 1.06, -1.55)],
     [0.06, 0.055, 0.05, 0.04, 0.02])
wisps(m, c, [(x, 0.42, z) for x in (-0.1, 0.1) for z in np.linspace(-0.5, 0.5, 5)], length=(0.15, 0.32))
models.append(m)

# ------------------------------------------------------------------------ 3: crawler
m = Mesh()
c = 'violet'
blob(m, c, (0, 0.95, 0.20), (0.22, 0.18, 0.30))
blob(m, c, (0, 0.86, -0.35), (0.18, 0.14, 0.16))
limb(m, c, [(0, 0.86, -0.35), (0, 0.90, -0.05), (0, 0.95, 0.25)], [0.15, 0.13, 0.17])
limb(m, c, [(0, 1.00, 0.46), (0, 0.92, 0.66), (0, 0.80, 0.77)], [0.07, 0.06, 0.06])
blob(m, c, (0, 0.74, 0.85), (0.11, 0.14, 0.12), amount=0.05)
blob(m, c, (0, 0.62, 0.90), (0.075, 0.05, 0.07), amount=0.03)  # (the jaw, hanging)


def crawler_arm(s):
    limb(m, c, [(0.20 * s, 1.00, 0.40), (0.38 * s, 1.18, 0.58), (0.37 * s, 0.55, 0.85), (0.36 * s, 0.06, 0.95)],
         [0.06, 0.045, 0.04, 0.035])
    for k in (-1, 0, 1):
        limb(m, 'bone', [(0.36 * s, 0.06, 0.95), (0.36 * s + 0.05 * k, 0.03, 1.08), (0.36 * s + 0.08 * k, 0.01, 1.2)],
             [0.02, 0.014, 0.004], seg=6)


both(crawler_arm)
both(lambda s: limb(m, c, [(0.14 * s, 0.86, -0.38), (0.30 * s, 0.55, -0.10), (0.25 * s, 0.10, -0.60),
                           (0.25 * s, 0.03, -0.48)], [0.08, 0.06, 0.045, 0.035]))
spikes(m, c, [(0, 1.10 - 0.08 * (z < 0), z) for z in np.linspace(-0.3, 0.45, 7)], length=0.07, radius=0.025)
wisps(m, c, [(x, 0.82, z) for x in (-0.12, 0.12) for z in np.linspace(-0.3, 0.4, 4)], length=(0.3, 0.6))
models.append(m)

# ------------------------------------------------------------------------ 4: tall one
m = Mesh()
c = 'black'
both(lambda s: limb(m, c, [(0.10 * s, 1.27, 0.0), (0.11 * s, 0.66, 0.03), (0.10 * s, 0.07, 0.0)],
                   [0.07, 0.045, 0.035]))
both(lambda s: ellipsoid(m, c, (0.10 * s, 0.03, 0.08), (0.045, 0.03, 0.11), nlat=6, nlon=8))
blob(m, c, (0, 1.30, 0.0), (0.15, 0.10, 0.09))
limb(m, c, [(0, 1.30, 0.0), (0, 1.65, -0.02), (0, 1.95, 0.02), (0, 2.10, 0.06)], [0.12, 0.10, 0.15, 0.13])
blob(m, c, (0, 1.92, 0.02), (0.19, 0.18, 0.11), amount=0.05)


def tall_arm(s):
    limb(m, c, [(0.18 * s, 2.06, 0.04), (0.27 * s, 1.65, 0.02), (0.30 * s, 1.20, 0.08), (0.31 * s, 0.78, 0.10)],
         [0.05, 0.04, 0.03, 0.025])
    for k in (-1, 0, 1):
        limb(m, c, [(0.31 * s, 0.78, 0.10), (0.31 * s + 0.02 * k, 0.65, 0.11 + 0.02 * k),
                    (0.30 * s + 0.03 * k, 0.52, 0.10 + 0.03 * k)], [0.012, 0.009, 0.002], seg=5)


both(tall_arm)
limb(m, c, [(0, 2.12, 0.06), (0, 2.30, 0.10)], [0.05, 0.045])
blob(m, c, (0, 2.42, 0.12), (0.09, 0.14, 0.10), amount=0.04, rot=rot_x(0.25))
wisps(m, c, [(0.18 * s, 2.0, z) for s in (-1, 1) for z in (-0.05, 0.05)] +
      [(x, 1.25, z) for x in (-0.12, 0.0, 0.12) for z in (-0.06, 0.06)], length=(0.5, 1.1), radius=0.03)
models.append(m)

# ------------------------------------------------------------------------ 5: hunched one
m = Mesh()
c = 'slate'
both(lambda s: limb(m, c, [(0.18 * s, 0.86, -0.10), (0.22 * s, 0.45, 0.08), (0.20 * s, 0.08, -0.05)],
                   [0.15, 0.11, 0.08]))
both(lambda s: ellipsoid(m, c, (0.20 * s, 0.04, 0.04), (0.09, 0.045, 0.14), nlat=6, nlon=8))
blob(m, c, (0, 0.94, -0.12), (0.26, 0.18, 0.20))
blob(m, c, (0, 1.36, 0.04), (0.42, 0.40, 0.36), amount=0.1)
blob(m, c, (0, 1.66, -0.08), (0.30, 0.25, 0.28), amount=0.1)
blob(m, c, (0, 1.34, 0.48), (0.15, 0.14, 0.15), amount=0.05)
blob(m, c, (0, 1.24, 0.55), (0.12, 0.07, 0.10), amount=0.03)


def brute_arm(s):
    limb(m, c, [(0.36 * s, 1.55, 0.15), (0.50 * s, 1.00, 0.30), (0.45 * s, 0.22, 0.42)], [0.14, 0.11, 0.09])
    blob(m, c, (0.45 * s, 0.11, 0.45), (0.11, 0.10, 0.13), amount=0.05)
    for k in (-1, 0, 1):
        limb(m, 'bone', [(0.45 * s + 0.05 * k, 0.06, 0.52), (0.45 * s + 0.06 * k, 0.02, 0.64)], [0.025, 0.004], seg=6)


both(brute_arm)
spikes(m, 'bone', [(0.15 * math.cos(a), 1.82 + 0.05 * math.sin(a), -0.08 + 0.15 * math.sin(a))
                   for a in np.linspace(0, 2 * math.pi, 7)[:-1]], length=0.22, radius=0.04)
wisps(m, c, [(0.3 * math.cos(a), 1.05, 0.25 * math.sin(a)) for a in np.linspace(0, 2 * math.pi, 9)[:-1]],
      length=(0.3, 0.6), radius=0.035)
models.append(m)

# ------------------------------------------------------------------------ 6: goat man
m = Mesh()
c, b = 'rust', 'bone'
both(lambda s: limb(m, c, [(0.13 * s, 1.05, -0.05), (0.15 * s, 0.72, 0.18), (0.14 * s, 0.35, -0.15),
                           (0.13 * s, 0.05, -0.02)], [0.11, 0.07, 0.05, 0.045]))
both(lambda s: ellipsoid(m, b, (0.13 * s, 0.04, 0.0), (0.05, 0.04, 0.06), nlat=6, nlon=8))
blob(m, c, (0, 1.08, -0.05), (0.18, 0.12, 0.13))
limb(m, c, [(0, 1.08, -0.05), (0, 1.40, 0.00), (0, 1.70, 0.08)], [0.17, 0.15, 0.20])
blob(m, c, (0, 1.62, 0.08), (0.25, 0.22, 0.17), amount=0.06)


def goat_arm(s):
    limb(m, c, [(0.24 * s, 1.75, 0.08), (0.32 * s, 1.35, 0.0), (0.30 * s, 1.00, 0.12)], [0.07, 0.055, 0.04])
    for k in (-1, 0, 1):
        limb(m, b, [(0.30 * s, 1.00, 0.12), (0.30 * s + 0.03 * k, 0.90, 0.15), (0.30 * s + 0.04 * k, 0.82, 0.20)],
             [0.015, 0.01, 0.002], seg=5)


both(goat_arm)
limb(m, c, [(0, 1.80, 0.10), (0, 1.95, 0.18)], [0.08, 0.075])
blob(m, c, (0, 2.02, 0.22), (0.11, 0.12, 0.13), amount=0.04)
limb(m, c, [(0, 2.00, 0.30), (0, 1.90, 0.50)], [0.08, 0.045])
both(lambda s: limb(m, b, [(0.07 * s, 2.12, 0.20), (0.16 * s, 2.30, 0.08), (0.22 * s, 2.30, -0.12),
                           (0.20 * s, 2.12, -0.15), (0.24 * s, 2.00, -0.05)], [0.045, 0.035, 0.025, 0.015, 0.004]))
both(lambda s: limb(m, c, [(0.10 * s, 2.06, 0.20), (0.24 * s, 2.02, 0.18)], [0.03, 0.004], seg=6))
limb(m, c, [(0, 1.05, -0.17), (0, 0.95, -0.30)], [0.04, 0.005])
wisps(m, c, [(0, 1.88, 0.42)], length=(0.25, 0.3), radius=0.02)  # (a beard)
wisps(m, c, [(0.2 * math.cos(a), 1.05, -0.05 + 0.14 * math.sin(a)) for a in np.linspace(0, 2 * math.pi, 7)[:-1]],
      length=(0.3, 0.55))
models.append(m)

# ------------------------------------------------------------------------ 7: crow man
m = Mesh()
c, b = 'violet', 'bone'


def bird_leg(s):
    limb(m, c, [(0.12 * s, 0.82, -0.05), (0.13 * s, 0.50, 0.12), (0.12 * s, 0.18, -0.05), (0.12 * s, 0.03, 0.0)],
         [0.08, 0.04, 0.03, 0.025])
    for k in (-1, 0, 1):
        limb(m, b, [(0.12 * s, 0.03, 0.0), (0.12 * s + 0.07 * k, 0.015, 0.14 - 0.04 * abs(k))], [0.015, 0.004], seg=5)
    limb(m, b, [(0.12 * s, 0.03, 0.0), (0.12 * s, 0.015, -0.1)], [0.012, 0.003], seg=5)


both(bird_leg)
blob(m, c, (0, 1.15, 0.05), (0.28, 0.42, 0.28), rot=rot_x(0.4), amount=0.1)
limb(m, c, [(0, 1.45, 0.20), (0, 1.60, 0.30)], [0.10, 0.09])
blob(m, c, (0, 1.68, 0.36), (0.12, 0.12, 0.13), amount=0.04)
limb(m, b, [(0, 1.68, 0.45), (0, 1.63, 0.62), (0, 1.56, 0.78)], [0.055, 0.03, 0.004], seg=7)
limb(m, b, [(0, 1.62, 0.45), (0, 1.58, 0.60)], [0.04, 0.004], seg=6)


def wing(s):
    arm = [np.array(p) for p in [(0.24 * s, 1.42, 0.05), (0.38 * s, 1.22, -0.05), (0.42 * s, 0.92, -0.10)]]
    tube(m, c, arm, [0.06, 0.045, 0.03], seg=8, per_segment=4)
    for i, k in enumerate(np.linspace(0.0, 1.0, 7)):
        j = min(int(k * 2), 1)
        p = arm[j] + (arm[j + 1] - arm[j]) * (k * 2 - j)
        L = 0.45 + 0.35 * k + rng.uniform(-0.05, 0.05)
        d = np.array([0.08 * s, -1.0, -0.25 - 0.1 * k])
        d /= np.linalg.norm(d)
        tube(m, c, [p, p + d * L * 0.5, p + d * L], [0.035, 0.025, 0.003], seg=6, per_segment=2)


both(wing)
for k in np.linspace(-0.12, 0.12, 5):
    limb(m, c, [(k * 0.5, 0.95, -0.2), (k, 0.75, -0.42), (k * 1.5, 0.55, -0.55)], [0.035, 0.025, 0.003], seg=6)
spikes(m, c, [(0.05 * math.cos(a), 1.75, 0.32 + 0.05 * math.sin(a)) for a in np.linspace(0, 2 * math.pi, 6)[:-1]],
       up=(0, 0.6, -1), length=0.14, radius=0.02)
wisps(m, c, [(0.2 * math.cos(a), 0.85, 0.05 + 0.18 * math.sin(a)) for a in np.linspace(0, 2 * math.pi, 8)[:-1]],
      length=(0.25, 0.5))
models.append(m)

write_mtl('shades.mtl')
for n, m in enumerate(models):
    m.write(f'shade_{n}.obj', 'shades.mtl', f'shade_{n}')
