"""Generates puddle.obj / puddle.mtl: a placeholder for a puddle of water, a flat blue square
(SIZE metres a side, centred on the origin, on y = 0, facing up). The giant mosquito lays its
eggs in it (see Mosquito). Meters, Y up, like the rest of the project.
"""
SIZE = 4.0
COLOUR = (0.10, 0.30, 0.72)

h = SIZE / 2
with open('puddle.mtl', 'w') as f:
    f.write('# generated by generate_puddle.py\nnewmtl water\n'
            f'Ka {COLOUR[0]} {COLOUR[1]} {COLOUR[2]}\nKd {COLOUR[0]} {COLOUR[1]} {COLOUR[2]}\n'
            'Ks 0.6 0.6 0.6\nNs 80\nillum 2\n')
with open('puddle.obj', 'w') as f:
    f.write('# generated by generate_puddle.py\nmtllib puddle.mtl\no puddle\nusemtl water\n')
    for x, z in ((-h, -h), (-h, h), (h, h), (h, -h)):
        f.write(f'v {x} 0 {z}\n')
    f.write('vn 0 1 0\nf 1//1 2//1 3//1 4//1\n')
print('puddle.obj:', SIZE, 'm square')
