"""Generates floor.obj / floor.mtl / floor_grid.png: the empty floor of the creature testing tool
(src/creature_testing.cpp): a flat square, 100 x 100 m, with a 1 m grid on it so that a foot that
slides, or a body that moves too far past its feet, can be seen against it. The floor is a regular
grid of vertices (Stage's HeightField mode needs one). Run it again if the numbers change."""
import numpy as np
from PIL import Image

HALF = 50.0     # metres from the middle to the edge
CELLS = 20      # cells per side (a regular grid, 5 m each)
TILE = 4.0      # metres the texture covers before it repeats (4 x 4 squares of 1 m)
PX = 1024

# the texture: 1 m squares, two tones, a thin dark line on every edge, and a thicker one every 4 m
cell = PX // 4
img = np.zeros((PX, PX, 3), np.uint8)
for i in range(4):
    for j in range(4):
        tone = 150 if (i + j) % 2 == 0 else 120
        img[i*cell:(i+1)*cell, j*cell:(j+1)*cell] = tone
img[:, ::cell] = 70
for k in range(1, 3):
    img[:, k::cell] = 70
    img[k::cell, :] = 70
img[::cell, :] = 70
img[:, :4] = 30
img[:4, :] = 30
Image.fromarray(img).save('floor_grid.png')

with open('floor.mtl', 'w') as f:
    f.write('# generated by generate_floor.py\nnewmtl floor\nNs 5\nKa 1 1 1\nKd 1 1 1\nKs 0 0 0\nillum 1\nmap_Kd floor_grid.png\n')

n = CELLS + 1
with open('floor.obj', 'w') as f:
    f.write('# generated by generate_floor.py\nmtllib floor.mtl\no floor\nusemtl floor\n')
    for r in range(n):
        for c in range(n):
            x, z = -HALF + 2 * HALF * c / CELLS, -HALF + 2 * HALF * r / CELLS
            f.write('v %.5f 0.00000 %.5f\n' % (x, z))
    for r in range(n):
        for c in range(n):
            x, z = -HALF + 2 * HALF * c / CELLS, -HALF + 2 * HALF * r / CELLS
            f.write('vt %.5f %.5f\n' % (x / TILE, z / TILE))
    f.write('vn 0 1 0\n')
    for r in range(CELLS):
        for c in range(CELLS):
            a, b, d, e = r*n + c + 1, r*n + c + 2, (r+1)*n + c + 1, (r+1)*n + c + 2
            # counter-clockwise seen from above (+y)
            f.write('f %d/%d/1 %d/%d/1 %d/%d/1\n' % (a, a, d, d, b, b))
            f.write('f %d/%d/1 %d/%d/1 %d/%d/1\n' % (b, b, d, d, e, e))
print('floor.obj:', n * n, 'vertices')
